apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
  name: rook-csi-cephfs-node-user
data:
  #ENC[AES256_GCM,data:zat/x4fFjjY0iKt4CIuli8YUB0ZfjwkbE5l7FCdszOFZMSwp4oMMUPfaorExh/YQ9nyFjFFFT0fyzLHBqyiXbshe,iv:ymyAKFJIDQSxZQ/rhPuAOF+ckqwxZzQZ3+oCP9uLDwE=,tag:z4cDEfOTvH9egwWIAEm17w==,type:comment]
  #ENC[AES256_GCM,data:oTlMPYrrPKgu1PNHMpp8xqBNoQWjhrjoFj//8Qtl,iv:g1CzzgAYHZds0hjUprt7tnCV0XkLl1vqDplEYGb1m/0=,tag:3n+DpARWmaJU6fjPNFnjig==,type:comment]
  #ENC[AES256_GCM,data:4mHelIuTtO44nPX9c3zVMAoTnJzcZzx1nokegfyqeIwX58Xa9jnUZ2Y/hcR0hjGxVMaTc8lSWWEBMx6YuXKrdnfxw/a0A8KBGpP1GAE=,iv:E3OsgoC43ElMZddGr8TstKS13i4o7G8nSA+Fp8WZexc=,tag:yZqm1mtctFZl/FwOr5ZdBw==,type:comment]
  userID: ENC[AES256_GCM,data:4PJK1u0vPTl62TZdMG1dY8JUycI=,iv:pCx7DYVxupXHnqT53oK15riqYLduMF4JE9pQWDz7//c=,tag:F7LxJrfPsLTlgdR5NTUHeg==,type:str]
  userKey: ENC[AES256_GCM,data:9q64viUrqoSmFJqVyrCrJjcFVL8nvbia76w5SM4dyJNe7HTcVIaN1mOE39+YEWSS/34/WKkIIHY=,iv:ukbA/0fBfIGPzv/JZgPQfVyUqi/ZbvUhhQYrVq+0Thw=,tag:Uj+CCKso65GZUfqMptfCxw==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjVVNFIyZ29SYUt1U2pP
        ZE9idGFvRGFINGdTcTBzdmgyc2t1V3ZHTXdBCnVsdnB3cERTcGR5Y2VhaDAwWWUy
        RzkwbHZXVTIxeU9GVFU1R2JDVS9VdlEKLS0tIDhzUTl3bVN0RWl6RnlNSm5sbFd5
        MTlmRS9hVTJTdFgrdkswL25jWERMb1kK8pfVhIgwO6QV8f8pitY+xmtJgNz4530D
        DNTZVrWM9dD6hR/iv4XFPFri1PENgGNK5Q+J24ew657jgAgT/5xrgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T09:09:10Z"
  mac: ENC[AES256_GCM,data:KSVgWX6Rjji5sPvMsetksfdpDAjtuOnTQFZjJajd/qKyL+by/Vcb9rpVMEUioyWylk+PfxJWi52zDlllGTMwwWm8xYjvHYCZEI7N80pcwITDKOGqbmLvkk348vowd4o/M+Vyl8kGwIURsniXrlZB9QQQ4wQg3a3VYXBKAtnmyL0=,iv:GP2QIurrHNCGmiPP7D81jj640lfeLyE5CF5A1ALVEeg=,tag:RNHpEbn6W8IFQNjv+OmkGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
