---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coder-secret
    template:
      data:
        ssh-privkey: "{{ .ssh_privkey }}"
        ssh-pubkey: "{{ .ssh_pubkey }}"
        age.agekey: "{{ .agekey }}"
  dataFrom:
  - extract:
      key: coder
  - extract:
      key: volsync-template
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coder-secret-env
    template:
      data:
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RESTIC_REPOSITORY: s3:https://{{ .CLOUDFLARE_RESTIC_REPO }}/${CLUSTER_NAME}/pvcs/${NAMESPACE}/${APP}
        AWS_ACCESS_KEY_ID: "{{ .CLOUDFLARE_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .CLOUDFLARE_AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
  - extract:
      key: coder
  - extract:
      key: volsync-template
