apiVersion: v1
kind: Secret
metadata:
  name: coder-secrets
type: Opaque
stringData:
  ssh-privkey: ENC[AES256_GCM,data:9+4KSf0zuLSrZlnJvuYaonAzXtwnVnfrGXx+iJeKezNIAlVGFUCz+Zsoj7qO6tNf21pJq+p4lsPtZzCowMX45xg/sRiaC1yyUJE6g/bvQ733OJO0tpjYKVB/F7YGmtLFjnYUM7rKprmsBg/QzpVMN5qbbxWWcv7z4TuepRBeRRngNOFy/qhNJKvlwog/kDrUVRxfJKA6KPedXC0kinJCnDjODDLUVE2SXJFWstfqaabwKFKYEKuduUUe48hRo0ZdbOlbJsdlJxqK3BMrIHnIRkKG2yJLu8XIVTsshYmkxWJ87Tz7TV+s/Y493m50aqD2aq1HVggWXvceeAyj0cQ8Py7DhghAlKHjLHMaAwlkHkXJOC++dVxVmTbFN5Biojorc1IjvLt5FI6dRerprS0o1Q2tAQGynAH+AgVBx7tA70Vg4dOpswafgCzOiuZmMRYcW1Pgk6tAJPD+nBUycwpzkoG/vwFITdbVmc99paR6/u+QanThzIwjtOawtwGr1873PuA5f1dAchHN8IeJ3/9Z,iv:HQ/4pojx8ofMG8VL/UZFhc5L5DZRIPEXkdonAgC1W/E=,tag:AcpkWyZvz14gqQ3qJfQJ5A==,type:str]
  ssh-pubkey: ENC[AES256_GCM,data:/RGvASdbWpQtOiz7w8Jp1wK/FafDeQvm8TuEel7nNvnR99JA/EVUpVXGfRkwwaUFyHKMm6JMNHNwluKNcM4laB3sCiG08+MdAX/WOn0D2XZ8FX3fvkmRPgoubJVjOJzq,iv:QmdFsX+sj+0tFcpn/lvFhLqc5fZxRC4otCRT0JDXpOg=,tag:BHId/quvUrpwPgdA8tnLCQ==,type:str]
  age.agekey: ENC[AES256_GCM,data:zU/2JDQSYDV21jmAo2967fRkl5uJKnSk5VkkdWJrnUd+M2coVWfPL6bA84/NUgAaTsdV/EklD35FNAyrvWjBNXfVyAJ4ipAZmp0=,iv:wIRPgD8Qp+uxROECzwpljvI0ifKqFUdnt0G3KYfccA0=,tag:fAqFNNaIachPwgHTi1Cm/g==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaEMzMW9xRlBaQUdSK1Zz
        RFNENmhSUVI1dmh2NjY5d1AweS9MTGtKakJFCnhLRlYrZFQ5QTBxdlY1Uzc4Q1lS
        ZVMrdGQ0eU1qVEVNMkU5REZNUzlERXMKLS0tIDk3Zi96dHF5REhsYzlXYVM0aVZ3
        L0E0TExCVDVFRjhxQU5CRXVxYzRyRHcKZyjaWXpSlMG641kJXTS63JFIFnyAMQH5
        73Er9to3P2RJYtDm86xjJd3HykOaz+1u4m1vgTckJcULBMvIUQ8nbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T06:13:19Z"
  mac: ENC[AES256_GCM,data:cL9aHNSIws6K0BJwrGDzEPJ7xbwN8XHAZ/oDXkKTib+fpKu1q6LINAh7InlrrY/+bO2P/7yK14jQzJE8YhlJyTXGK2Rp33+qPNd1XAYC6VylWk+vuzem7woMsSkVvmr2deD8Lq71Rv9ZQYYAGCCFNl6Z8BHw2uumg5OYanbYinM=,iv:lwNT4N7n7mYNy6Kc/u4ZJGaOh8FzRCkG/fhptb7jTEM=,tag:AAZPew3zW2LBzxd3DGMr7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
