kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: frigate-secrets
stringData:
  PLUS_API_KEY: ENC[AES256_GCM,data:29LOt0YiLArhMpQklsRFD9ZOSp2sz4txFZh3wRS4QiViCJE/XsFM0wK97+sHwmOSoHm8tEfVB9KBpEB6vi4zWEkOrcxC4OOSwXLzoW8=,iv:Q9uoUDSsK19dNe39/3Llq6sRz12YR7ACwzot3sS3+f8=,tag:DqE+LMGJ6JQlV0cdK3Mndw==,type:str]
  FRIGATE_GENAI_API_KEY: ENC[AES256_GCM,data:HoYiZEeg/A1yFxMLOp8NWYzdcyeyNCOHWBvQlQtA3FutUf9Qo39X,iv:3E0LFNJbKC9H6ybOBq/JLvgETKV1OrrI3jc9PIaAgs8=,tag:+IGZnxtj1aZBoKKs2pwoyQ==,type:str]
  FRIGATE_MQTT_SERVER: ENC[AES256_GCM,data:KrGDosrBteoh7/uGe/JEzlznCSQ=,iv:vzb+huJm/69q3cbtyb6kzOy+cO7AAMxXPM1lPsaLD6M=,tag:pm8ktdNnC+wWy3Jd3NkEeQ==,type:str]
  FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:4AqMbFN5lQ==,iv:LSZHGsyI2x1iaqE8vcp4XUMT8ohM7WTBXYOqPSR062Y=,tag:woJQS16OFHe8v1zirhf5kQ==,type:str]
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:IYSb7jxTOJLP2PeA3fL8jQ==,iv:k9GzalvKRr4Hq8VwxYaYBNwOmchgOw35UorQKGSpcns=,tag:EZ25iz/+vvKYhtftph58lg==,type:str]
  FRIGATE_CAMERA_1_HOST: ENC[AES256_GCM,data:DWStrt4s8t3KP32ellfvEVHdNDwWjGfPXDBRez8deL+NLuTnU6U=,iv:2wGoH0CWnEKCX9dSKc9yxqvWglwCBHujW6YEFr5vyUs=,tag:krBhVgqsdONyfRPb9fZ35Q==,type:str]
  FRIGATE_CAMERA_2_HOST: ENC[AES256_GCM,data:mYhyaLJRD3of8jgHBWDYlzXle3lmH2SPMu0HgcY=,iv:iHAaVlCrxMzrDVNih8+vVT9a0h1qTt0xHDk+L0EkwIU=,tag:id4sPExY+tHjHa1hZsagdQ==,type:str]
  FRIGATE_CAMERA_3_HOST: ENC[AES256_GCM,data:MgtRDYdD2yc9bXI03URgvSy8IuxrM4GlcRR+j9xwP0gmGQ==,iv:MOPdciGGAtshtkHMhrzqZUvxo5DxMNiaajiuVSXhCEg=,tag:ge0go+1zAs9qL/EqQ2ihOA==,type:str]
  FRIGATE_CAMERA_4_HOST: ENC[AES256_GCM,data:0ZoW2gIHlfNNru5VkU7/lpljzir55U4lfxdLSsalrJrYOxU=,iv:2oQsZaiTkomRH/7+16mpbPxot88R0eBjHVJrShoZDQU=,tag:hiwCM1ExAcHXJxQh7HM2oQ==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMU9XRncyOGdtSFB2bzcr
        Z2xJaDllM1pXWVVFT2ZRMDF4ZDQ3TGZCWjNZCmRicmoxQ2R4UGRlYzlRREF5ZXNt
        SWJhOXRXR2NnbXdyT0hVZ3JKUHF0OXMKLS0tIEgzQzRoQ2VhUXhXVk9EdmM2TDJO
        TU9QR3lIR3ovUVRFRTNRWUcveDFyVUUKFi81QNVy1IW3NsqtZBm5k/9rWCpA40G6
        Rm2eT302sOyoVfqIJ4yfFRb70b/Wxsb4XfEsHGLq5hu8QS8HvsqJEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T17:45:12Z"
  mac: ENC[AES256_GCM,data:g2Vkwm1IsLt8plDkhrTYgzeVRkmEq1//XWlsQvR16sZVDmEm5ao/i6nr3tGbJAfo6IpucwgbuYhJWEka/ccJ+jwf5sUREWtcpxfU7PhnZbAyHZyGMHiCZXH6OOaQTNDh5rIg5bL0K1lcVC6WTziFyXj3xVJSNPh/lUb0gFA0mrU=,iv:xOkqJeF92ioybwjm8lIohB91cHQFtYZbQyOwhnQS86g=,tag:gnbr9oyTQ0jObR6nSHh5oA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
