kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: emqx-secrets
stringData:
  EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:+9HYL5K8dBQ=,iv:KjDqYpEm7K/hD9NiaEqsor31/mU7qlF8jP3DurkkAmM=,tag:zncl+0hzvivR2bPZKlEGjw==,type:str]
  EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:xuXcf1rcKe+GMQ==,iv:6yCHG7A0u2rg5NXGmhJ/B9s0pn+Sq/QP3VcQDuVGqYk=,tag:GKkrO0WbNjCGi0ofCVQfhw==,type:str]
  #ENC[AES256_GCM,data:I6f+esW2+GPy+i03ATCB/R5waVbmg+PNc70b,iv:n8FkjsEEat7qmVZX+y9pLKGm1MvYYRVit2/3ILeBVFI=,tag:ELDGDJya4lf55STZSJjOSw==,type:comment]
  #ENC[AES256_GCM,data:2NySoHsOkTPP/jUw3B18rTP2NL1KNX6gcA==,iv:gRICZOjhDPJziwJAvNQuXfNI6hXy0QEVi0KFVVR17Y0=,tag:ypvN6upqoN9wK3KZ1qJrSQ==,type:comment]
  #ENC[AES256_GCM,data:gcbvuR1aOYpxnzIpe/a9/boMOxHOZHHB63XatDg3akWpMA==,iv:HsvTrGPZHotet95333mBHfibb/IUaUr7ALHQtlbz5tE=,tag:27kQpxc928t+HrTMjSI9sg==,type:comment]
  #ENC[AES256_GCM,data:Ig6EtMVombaBDlFVSow3HANrr4zVb0Wzhj7M1Hse6ME=,iv:DGmJEw8DoeEEzayQGMJUO6hF7coJsxmX01KBtlQ8GPY=,tag:9z9VEwbwEUs84GUb0a37cQ==,type:comment]
  #ENC[AES256_GCM,data:/CFR4EUCv8XioI2yQcZGUoj9A/7+egEj7yyO4yezUCd8+w==,iv:HzYl0wiWJDQgRV9mw5jKMTLc70295mjbJvns8IKDMoQ=,tag:pU45D45+vRvi7rb1Wu4cLQ==,type:comment]
  #ENC[AES256_GCM,data:k3ekfo7MhgLmj5EgjBNoAPioajT459C+Jek=,iv:Uk0opB7AS7GfwabipqfbB1ecNkAixGhl53aQ1gbP+GA=,tag:DlLjTCxktspNa1CNFaAu+Q==,type:comment]
  #ENC[AES256_GCM,data:hrZ7q+vMWxQwo78pLpoJoOUxt1dNvJvRuaPKJMTl+fCc,iv:3IIb6y7swgASqszNnuit4Zd1GqNcQgMKP8ctwlGfx2Y=,tag:4ov98MvjrCXxLxQE6WqHAw==,type:comment]
  #ENC[AES256_GCM,data:vDn6wOqifZEcSzMkhkW0mtgd8w19KIFyOBO9KRo=,iv:MuGh9DukXX1l/BPOo21rkn9PiUgpq14imqPgJy8tnSQ=,tag:/0QEHH8OUJJGX2bu0VSvnQ==,type:comment]
  #ENC[AES256_GCM,data:fIUGiPnd0jfVZeEi7b0MuOGEeeg5UbbgKsW7IeH9Enf6dw==,iv:LcisVOHB77qQOQDVORUEhGcJNB7KGjg6hdHElxpwrl0=,tag:/5YuzhyKsansFaqy3438BA==,type:comment]
  #ENC[AES256_GCM,data:JGbR3Encu0ujzzaXR1j5BZmNFdT71g==,iv:B8z3SfhgPXtCI//5fq7RjeVAVwjBbmhbrMHRaYo7Cmg=,tag:yK9xoZpLyCAj0IGTzPWlGw==,type:comment]
  #ENC[AES256_GCM,data:lqNX/5/WMkpor0uHDnqhS6xG2SCyHd5O0xLDYw8NMycW8g==,iv:c+/KBNNqzVN8txwLoETuN74bDizjb/067yjjIUVDnPg=,tag:CiXyfqC1CBt6G/6dkX6LVA==,type:comment]
  #ENC[AES256_GCM,data:6G7zzQRbUwxvpM5Kot9T/qf6vIJtPdTPBA==,iv:itX4YGdC0xQiZTvurtOzS7HtTMrJdMHL1IXjrr0Nb/U=,tag:KfduvY2USk18S9NPxmN42A==,type:comment]
  #ENC[AES256_GCM,data:iUPDiKDSaI2FalC06jacPycxKodQombIXUW9NFFkOBybwtai/zrUMw==,iv:qJmACOneHE3mjWpXjyEb6YGXAT0cz2yK+9yTPoWnTOE=,tag:M2+mfkzhJUSbnHG0QiZOGg==,type:comment]
  #ENC[AES256_GCM,data:KQv4vCknK3dRdKlg3RXGom2fsyn8SGE7kRo=,iv:Z98stHW9LKysWxINQKQJAX6eDVbJmqB96S47LcalG6w=,tag:CKLlBf6iSDKasoJKJr4lbg==,type:comment]
  #ENC[AES256_GCM,data:YO3SSPjPtJSRwn1BZTbW+llv45HuyDYyhtyRk012YHkvSk2tNkg=,iv:Z1jeueMX5O3+Taf9oPax+OmIU9T/P4MDQwAySIwNSLs=,tag:pl3Mmn4IdeyezCfBpSei/Q==,type:comment]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbFhnRmFJV3hhZG9QZ3dP
        emx2TVpCdXRFcVdJR054c2w2Zy92V3lRU3dFCnd0ZWw2VDhQY1FTU0MwSjNjbVZZ
        eDBuZHVIa0M2SmVWZ3dzazU2Y2Zpam8KLS0tIGpRSHFsZFQySFlyK0sycnFCZjFV
        TzM2NkJxWGVWK05pbTludlN3ZHZrYncKSIa6PqurSJmAFzgqGsoD6r0ap0sz0rab
        zbHbXQhfRS+uOnT7VmW1ak2p1hGcaBNmPhOzX1zp7ZzQXp1F+sUB7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T20:20:35Z"
  mac: ENC[AES256_GCM,data:4w2w3mjiBi2u3nCeAyTTOOW3NwrZtTR6bp29+sWfNwdcJQdgdBJET7hsdFpR3vFMqdimx6cb5ZmlqSGNHrmiWXM+Q72fqGTpnkIOpMxg0jinkIWfR0m8zlnN2MLAI7gf3CmCQ3Uak+avVKRQY/7+HlId5YNdng8mGY59e6LWmbI=,iv:GqREUkpCYlKIyoGOeP0p7FcygXo2d1Yey2tbLJo0RKU=,tag:GaEZeM9LknhcNJdVGb7HFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: emqx-init-user-secret
stringData:
  init-user.json: ENC[AES256_GCM,data:M36PfMBsXkAcdziQ8RToXNtBRMjwMq45hpjz0qDQgwAOMpfxpFLH83KqHw2rLj++333pLmLjmg7dQ2enRgN+Q/SDccbz8xtx4TMyYLuMbX0UBREnesKKDcngdr0HtKFmNtxqrL+Ar/oX3GoizMk0kj3XsDHoezf5F29mvjbs3afzu196/ixOTlsSXs2cfa2Euakaq2VVmUN9RjkC2TKL80btqwh+XerDVNU4v/lbzn3um109Hy9JCAfMpdiuU4YYBleOFdoxrYqClRI5eVmE5wjP+CCrhWMP2PNAZhqY7Jlr9FST6/GsBOXskCQvdVvpph2GGwDLMXcLv/cNmtzvS0LaGjId1bVh2aO5o/vdSeojKPtK7JRwj1zA2Be0fLqHaLvwLtA9LDpz9FcRJXiTXenSaAZjLZatx/nvv8D4BU27w3fzl49mVsFbNi1Kc9nexf1j3zyda+h+J7JmR8GAUHTy83LW189RnMc592/29R6yTGvC5BBUPSkyqLzDoEpvDvwyCViWlyd+VTo1hxOhS2wb7+oK/3FL5693ATOIx/YDJl7NKslyRMDg6Rh5XydVlADjWLIUlnZq9ZUHv1Ds+XT5eAyXVG9wzA5qW1tzYJ/i1kWI5581Bzlp97XngK7jV1yhAD1fs65IlNwhB5cU4gLZrGCeuBSnp/RalM1TeUCSIoGDUdPGEkiUWE0CincTz5eVjp5D6Tc4N01iv5sENYuuhH0uJd+mMS4sQFj6YGcxL0IEjFwDFMq+jgYj4P2ARUmZ5B591KR9PBZ9BQ==,iv:gvqyh1dQjKwf2cESsm9j1ZaL8u0tZ/cmsJOvbZbdwRo=,tag:0JfyY7Mf8TCR37+4DdKuXw==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbFhnRmFJV3hhZG9QZ3dP
        emx2TVpCdXRFcVdJR054c2w2Zy92V3lRU3dFCnd0ZWw2VDhQY1FTU0MwSjNjbVZZ
        eDBuZHVIa0M2SmVWZ3dzazU2Y2Zpam8KLS0tIGpRSHFsZFQySFlyK0sycnFCZjFV
        TzM2NkJxWGVWK05pbTludlN3ZHZrYncKSIa6PqurSJmAFzgqGsoD6r0ap0sz0rab
        zbHbXQhfRS+uOnT7VmW1ak2p1hGcaBNmPhOzX1zp7ZzQXp1F+sUB7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T20:20:35Z"
  mac: ENC[AES256_GCM,data:4w2w3mjiBi2u3nCeAyTTOOW3NwrZtTR6bp29+sWfNwdcJQdgdBJET7hsdFpR3vFMqdimx6cb5ZmlqSGNHrmiWXM+Q72fqGTpnkIOpMxg0jinkIWfR0m8zlnN2MLAI7gf3CmCQ3Uak+avVKRQY/7+HlId5YNdng8mGY59e6LWmbI=,iv:GqREUkpCYlKIyoGOeP0p7FcygXo2d1Yey2tbLJo0RKU=,tag:GaEZeM9LknhcNJdVGb7HFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
