apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PDe5HjMxeiKL2dRXo0x7uAIKDmXwuj2kOVpaD+hWeOBB9DxANm8RPg==,iv:cMNpmr4wS7gpoie5gC6K1Rg3jGWsaPCC7ysxeCtc3Q8=,tag:FuFbsP2CyKhl1AyUbTZI3Q==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdWhxNFlrK0w1eW1vYit5
        aHVWd3lOaWZIaUlQSjZwQUg2RXRlYy9NZWxZCkU0MTB1em83U3NlWk1lcmlweGRV
        TnIxWWJ6dUJabmF2ZW5sUWt2NWRjWjQKLS0tIDN3ZTlqT0RpRE80bGg2enJXVC9M
        YjFydXM0WDk4SjlLUjJ5b1Y3U3lrL1kKmXuD7t+MQSxV/Cxu1Zt21MMXFLnJEjrJ
        vvwZcp4nHwhlBbY/9/J4HeD3VZ0eRC7u44Q5AAHvMI6RllEyoQeYeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T06:30:11Z"
  mac: ENC[AES256_GCM,data:howwkOsePmc+73a7UiuxZ5wfYJ4j/jjgN1cEqScEBrfraeCckJCorkiPLFtLfkpHW4TTYpD9T1rlVu0zL6Ym1vI5nXUU9VR+7mLYS2GxitN9GWgTqTEkCHetM+hjNJiLeoRltY+m8B1GCsHRpG4ntrKTxdt2pVWU0Hd2rbqy/10=,iv:5GEN/0c8rMeVXBQUr1F9VlcNnfz047E4ZiC067LzvpQ=,tag:/vQE+6XSygDrojtAu3l4KQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
