apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:EMr4xP+EFc23ULsQSUDF1LI+xprdUhd0mTdy8VVWZV6aAVMZcN6uXw==,iv:OIMkw2zno3R7oTOFOk9Ca4HKf/gOWgQY2E9mNOk4s8c=,tag:L8kZa2Z52HQFHPNSABMLJw==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOHRrcnlyNDZPVm4yZGQy
        UTZzTWdWZlhEay9DaERzVXFBb0daUjVMQ2xBCnJaK0pOWUpUdW9zNmlkSnphaDBr
        Um55QWhwMm9TZldZTEdsN0RrblJ0a1UKLS0tIHBVOFBpYkhjNmhiMkcxRjlhSnIy
        OTB0Rzd5UU1aZWEwT3lISGV3emM4Y1EKZjDjWExNDAtHbi8RmyQse1pmBvTKY/JY
        ANsUVC5yI6cS+qtQPAEVmJHT9EPwnnsEVAR478FaZzPTcx7ReAn/SQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T05:59:00Z"
  mac: ENC[AES256_GCM,data:dKO/iimtVS942jhBPkRzKh5qTXhBWNr1JTXuaExaLv+uOcEnbAkf/B/Fd6XGF/rBZL7J/BhmHkFy3eI/8gVyMWnnz7uFs4Hu0fFGJONmFC9hFSHCDGfe6Nwcs0siH8g+sbMTahBl50+3h53Mk6IQRLVIMww2H70Q6xcfhjJBo8k=,iv:6as3N1NHsD8C5oUaKHpPGdmwfxdsRzqn6lBHlUpWObM=,tag:GazujkeKYWyyBdcowENp7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
