apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secret
type: Opaque
stringData:
  AUTOPULSE__AUTH__USERNAME: ENC[AES256_GCM,data:tAPfZbQ1MZ8=,iv:SQpPaw/JWRYqTFItrF3aGa91quVgQSwEdAQExCZkWtM=,tag:ehkohKpttb0GH5SSHdJ9tQ==,type:str]
  AUTOPULSE__AUTH__PASSWORD: ENC[AES256_GCM,data:SEJrhb0VFCBaCQ==,iv:8NgEFaUV0sucgtOcEVktnt/HCC7wwf2ON8EEdAAWCPY=,tag:epfcutP6uxFauWsRLTd+Tw==,type:str]
  AUTOPULSE__TARGETS__PLEX__TOKEN: ENC[AES256_GCM,data:RRu0BiWP/2fx/uaO73HyH7IH43U=,iv:Bm/H2T+JXKqjmGSItsP7C72R2ebVoq4tgCcky7gc63k=,tag:IvoO5cy+oXFVU/tWXLLOAg==,type:str]
  AUTOPULSE__TARGETS__PLEX__URL: ENC[AES256_GCM,data:u5dCCa1+zw2hBaiGjTJOwOI79LAHl4FOcuaeWOSIGbxxxIMDelRrMjw=,iv:NZPjPVJhYukm1IW9QtNhsGdN1cVMwsOgBAG6IUgNa1A=,tag:X4CQvrhv1SEfwuDHSZCJRg==,type:str]
  FORCE_USERNAME: ENC[AES256_GCM,data:MKb1YfIuuzM=,iv:ri78I4z4XN+tWF3bopPRI+YJ639Rqlb9sXLpA7POB44=,tag:ytN3/IfpUY4rHsBtpad2pw==,type:str]
  FORCE_PASSWORD: ENC[AES256_GCM,data:A/JtJlux4OI1YQ==,iv:cN7Xj6IE9583P3bDna6j2cmC5LvXLT4kKj4D5ru09qU=,tag:cXQrVc83w6FA3+RDcNkCEQ==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL2xGZlJ0M0J3MVVhbzZT
        eTNYVHRSNjJPbXZlOHJXdytnRytNWWdxTFdJCjhlYmpKNTdPMCsyYUpPUkUwaWEy
        ZW82TDAvbE5hZFlDakJXTEZXeDVaMncKLS0tIEdndHE3QlVKSlFtZkh5WWhKOStJ
        MmJ0UG10YzZVNVc5RGlXcCs0K28wVzQKKC2mxKrT14Jsw0IBkT3wKWwU35fAKCv7
        8DSjPOjRbuaK5vC43nltwEcHKUJI2oKEUhy50tlkFALAX7sw4Rnfyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T07:08:04Z"
  mac: ENC[AES256_GCM,data:E8CtgScENHuuL+A9cHq4aHd39ENXiBjhfwqrVn5550Ve+Qt/9YPvFtvfwRM65YFaAqANWlVrMAuFfRYw7ht3+JLpia10sEvKHQnHW8Mn1qRSsP5gyhnGgk82te9i3HRuVv2qrRb5Anp/93Yi/MfGPbeVG35ChQBH5oq2oWPswS8=,iv:Rxr37eK0J+Sqg85F0JiOJCgxJYaK4M8qctIUCNa0AVE=,tag:ZdYwmuA3PsN1LHy1s3Aypg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
