apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secret
type: Opaque
stringData:
  AUTOPULSE__AUTH__USERNAME: ENC[AES256_GCM,data:/C7HyFGvI9U=,iv:vOOZ/5GxQMH3x79ONSNQSt2D/MhUwARNuT30xl8jbGY=,tag:Ql18ZJB0PGJwpXzJbTThAQ==,type:str]
  AUTOPULSE__AUTH__PASSWORD: ENC[AES256_GCM,data:AOgWH2O6CCdaZA==,iv:KzMPovgqAA/QlXhsZL6F1BoL+GaKomkTu4oDvEhdX6Q=,tag:42it02JKy21KP54F7nWBKw==,type:str]
  AUTOPULSE__TARGETS__PLEX__TOKEN: ENC[AES256_GCM,data:DPYETTL1cG7u5MOq20bzjbTXv0o=,iv:8NHtJvq2XuNd7HrLxlvfsnFwOhId0x7hn3N7JfnxkTs=,tag:LTgDvumFCf9QZVlW6qFt2w==,type:str]
  FORCE_USERNAME: ENC[AES256_GCM,data:GuDYWrxebEY=,iv:S/C1e3hEzcgM/qJTKKk7ucC/hi2t4faXTO/QA+8FI0A=,tag:QXw8S0CPQVx1ROV8Fw6Qdg==,type:str]
  FORCE_PASSWORD: ENC[AES256_GCM,data:p/xE8NYrEBCcZw==,iv:v32ztb4+TJcQxv0C1klcBOZENijFgGGBh1CQAFSPkaE=,tag:L4+B0meAGrLdmAHBpBH1LA==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bWZ0TS9aRWE5WFVjYm5R
        cGpITXFQMU9GT2hXRStUWGpSanQvMEUxS1dvCjVXWVNuenZLR1NsZm04ajZya2Uy
        YW5FV1RRZ1k1RnpydW9LMkljek9NeWcKLS0tIFZuNVhqSUI5MDBWUXV4VUZ6MFdO
        OCt3RW1XYzZtNVlZb09GOVVvQnNJVWMKogjsIoa1TU7judaV82XyRlWcsMHhMXzu
        YVAKQvkCLxZZwE57vNhMQZ1T4FpSOeZK02aFPTfSeLF+OLG1rNknNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T07:01:50Z"
  mac: ENC[AES256_GCM,data:fKpV2n0nbMMNfBHOdHn/UyrTR3wzNQ/kSgFxc12Hg45NYu1Xxqoz+CnsNLCfwODqiTLrPZ0Y1JeQo9DPcAxN6vub4K49u/s5u12/GhWd1KjMXDF5UFXDI0qg+gt1OBed1uje8n+MmhjfQvJF+MPYoqVfbVmsLy/jjWXhXn/3R58=,iv:A1PhatYHliPOFGrWn3E7hY8RL92sacRKsf7OkdLCLSE=,tag:XLuj4p1lDjo5YrTzKGVo5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
