apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OCoeWgVuRVTLov/AVH9v,iv:HFVtB+TJPSPTiL3jSU+XDCxCZr82oHKnK+nDTeDyovA=,tag:5f7jUW6MFNcvuqW4vDJvbg==,type:str]
  #ENC[AES256_GCM,data:CuwUxo7MiMmZ7m34raDi/I+JfMc=,iv:SIC6XPTB5UMMmV5/urukJyFCrd9XMxiO+JNZJp4xtiI=,tag:STqxCSfyXwlrYi4i9yyMFw==,type:comment]
  CLOUDFLARE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ry4ttiD45UX7xibREs4tZ90/7tqxV1AqDGTzd1b5FO0=,iv:EpUbUaaUl+Cwtobpk0ln4XpbDecOMc4Zp4mCueCRiS8=,tag:kDbeoJGfKiGbTmYOVUYSIg==,type:str]
  CLOUDFLARE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JV8bZapI4poNjQFCdyCfJb0eJI06j86FCz1x+4xinaZRIpWmtcH6oV8NQN5wDxmLzQT/4TJ9/3Of68Cbz6lmtA==,iv:HrODr4VneXwe2FTHJvWdAIz38FeR0KfuicHtqibzH6s=,tag:GKphXZDW4UwzKYTQjW7Z/Q==,type:str]
  CLOUDFLARE_RESTIC_REPO: ENC[AES256_GCM,data:IJv4qK996OarEF5gWXlRXaRPy6f/xe4b0IaEjO7sQNn9+jEO2cfjvz/Ao1YGFApdkOaEa10yxKUY,iv:99V461mIttwUbvh3NNcyj7ohoWBiv9dq/b+nEZwMRXI=,tag:iOU3QW0EHVNhwC2bzkH5kQ==,type:str]
  #ENC[AES256_GCM,data:PmiY6WfQEFR+nEtdkVZU7w==,iv:hdBCqaPnzH1Tkecmj0DOnlQx0e3IEhKlPxF6OPzbJBo=,tag:2/8odG2sH+3XZtNoLP2IEw==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:bEH9wM9hyjJFbg==,iv:GBclqFgAADIHySMOkE4BNscDrVFBGemDclhnB99vEaM=,tag:VPPwtGxQX5P9Hbj+2dcPJw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mqkRoi2g6Pf3n2TamC2iCEin86Q=,iv:WAyTJ5MkLVSWG3KpXgO3vG0a9McGAM5D3iTG/f3FHWQ=,tag:9RlFhIOqMV6VKYIcCkvyVw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BypmT74eC/WhxOmLNdxpC+Z35GP93SgV4MzC8mXlJpakU1iPbo+J0Q==,iv:mn/woi4wsTfU17foYztgdiax4FOVyo444tb6vn8+JVs=,tag:FLLdRZexRbvBPQkcbWgP2g==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WFZ0TFkxM3ZBb0tzei9m
        STNSNkJ3dHd1Si9hN1ZYQkFMZmVneURBTjN3CjFzWTFjcUtleXRocG43V1pUTGpS
        MlZsVFpxMk9ObnhaNHJBaFUxZm9JcFEKLS0tIHF5b0JnYWpLZ2o5cGpJMTk0NlI1
        V1ZmeHJCWlFzOHVaZXJzdU0wUWY1OE0K1Dtg+1mU1MJ9Cl+YcvojzRXFi/MFINkn
        MT3021U/x+nWo3egpzNn0gnu/h9FjI+OXVtJQ40BwBA/jjKFvrGcPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T19:59:12Z"
  mac: ENC[AES256_GCM,data:9ipoIvZQurcWHhIK+Am5EOveSMw06l4QZsMieAoiiIkA4qfQvQ5F31pe2m1gy+59EuWsNJhNukzWgbhSA9PxaFRN5oW4KDf1gLWP0dtLK7/G/0THDzwDyqB0A1dfCOeeLu08JiDhAbpS6jyHdCGc7fMQ2Meya+dQCSzw0ieGq3w=,iv:ZNwfDmSQ7NVRbQTsSwCbEXd1bjr4HDcRRWbZegtYGoc=,tag:H51njiQnZmnDbKXV9KZn2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
