apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:e2zTnzzpjaYqEKrL7amY,iv:DDonz8Dc+YIOs7WLHDsWJHT12eSlyH+uK7I+NTkpXjs=,tag:+/M/rgKRT8Ay9QLa9/WFSw==,type:str]
  #ENC[AES256_GCM,data:dCpZJCAOXbhF5X3hl6D3J2bpZ58=,iv:RR4uWAsHgx5PcgEGIhsva33qgdTtB+V3bhvOop0B/i8=,tag:dtPHTEQYGkTHw4VFbQp8nw==,type:comment]
  CLOUDFLARE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AT8+uYiZ7ifb4+j2clznaQNtfQIWypW2TFhcxLhbnAY=,iv:QEQNKV1pwqMHoOXkKkXTyv+4GSM3yOy09yS3QFa0ivM=,tag:uGwJmWN2BtMfzUsfOohXdg==,type:str]
  CLOUDFLARE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:D9llyoWSzO+wut2W15wPLbIjFVZGTsGx4s+v+KlDPOXeMxxWiSu3+EWaedTxmlk4pdMhNTo2EZ0ckvj8dFCehg==,iv:IGwt0GLDEEng57yDhvbYQrnX/56wal9Z+4j67GEC3Gg=,tag:Z7B00zYD30hKIlSepQehbA==,type:str]
  CLOUDFLARE_RESTIC_REPO: ENC[AES256_GCM,data:S1RV2jjoHB/U7isJn8WPeAjF2F4IYZ3bYYiP3B6dSM7bFF8b0IKTmDT2GEj43PKzf7j1U9FxvG8S,iv:WsrtruUKKxT9mJaPhBQoGJtaQE3AQLPM2Oiq9Cc7f+c=,tag:huD9O1CzJ2jbvbqs8jTUrw==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:uHf3ajlyEzGo,iv:NCH+rjy6Wtv0jIdTU6+3gDKFL/TC6ca0Ma8vjF2UftQ=,tag:encs8HiKz/Xww8RNUAYfZQ==,type:str]
  #ENC[AES256_GCM,data:wQZ+eGREsV4qR0Ifgt/DFQ==,iv:O6E8nitCQjj8d8Uv7ZlIXziPEprmr9yr1dLEIK5JQAA=,tag:B5BQMH8RjruWIO3hIucSRg==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:/ke96RQHDRNb3A==,iv:jB9fN4L6Wf0XMoWaYj/895BGyeYe6r8cAd4NSEPyrJo=,tag:f9Uf0kaBIhZX4Plty/3tXQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Vlj6fY6MnUyzwq4mn3UrYtHHaiI=,iv:BAAYfGuk6JDB6BPCWm2GDzpf4YGFz6xRtbbaBtmlNwY=,tag:uI5PjWcDTC/j1/y3ZLXaHQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ga8spk/9vtElF3m4UVeCaXBqQz7HA/oR5hJAmnqDqbr4ZrIeYegQVQ==,iv:reaeneKVx4G7xX6EU2MzTCoJylp6c+gEd5qzl/4T/r4=,tag:6GGA43oePju6F9vEOUfqjA==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5REl4RTg3UGo3dG5qNWZU
        c2hVQkk4NkxVVWtYSGMwWWlRRHB5ejJDUDJNCkRWYzVoaFluUzNLaVRnc08zV1Jv
        cytGdEZCQm5pak1zdkFrTHBjcVlySGcKLS0tIHVqREJnR0VvdDRoQk1vaEhEd1p2
        cHpZOHBoUEpwTy8ybnBPQ3FjcEhUYk0KAm0Ly1sAW+qyYDAdJjb7e7uRmYOKLBTJ
        ZoflHm9JVRZ+6YDuWRBEmx75BuinoSjjiVGXwGL3gcRD7aOAwpXDIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T20:10:35Z"
  mac: ENC[AES256_GCM,data:woX5wiAq0KysqF3rLtQ2RoS+GmnOCwQCa+x74pEFVtGxSytakfFHDXL+wxBAOekPtGRR/fNtTAHytyXlrnEJ13w91MMTn9bsBsmyOCwkDlHroc0u/snpEVWo/IINoQkCm16oZxL7NMke5eBBQW8M1/yOxU30uGGqxGQjWxuNn6o=,iv:Er7GAbiX8RDwB7tVWY5g87VuPxeUF8o4W2qwYI0L41Q=,tag:0Jv35N5SMND1chXzAcIAPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
