apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xTuS4UT+ZebRUYkmbQ4C,iv:BU8IADjg5dni5uJPwCMzyfDHGEwLTIM6+emwLeagjYo=,tag:18/WT8HdZdrR7nm6XKtsEg==,type:str]
  #ENC[AES256_GCM,data:P1vmXrALd0Tj4MEpmqdab9Hb9a0=,iv:WpD22HNRgCBREy84Fwc9CXgpOHL2u8AtFQ5JBoI7FMY=,tag:HzT75d7flTJrFrbRpzKMLA==,type:comment]
  CLOUDFLARE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HRv3AQzRbuSEW3dwpRARHTSI9XWFeGFwfL8d/IJQt+g=,iv:EBq83WSkMXmJ/Uaoo9zHpDZxNlPgvW9m8WAws81Fzhk=,tag:cQC2H1Bv1ZkRcXiL3vOLpw==,type:str]
  CLOUDFLARE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:toAxvh8pumG7ZUFfx5CVS0k0O+HoDOtHFKHpfnbYYJ57bl2MC3s5otxtKC1uwRF5ByP9a7+bNxiVsOqnE2HJsw==,iv:fbDEwmsLsmYoQD7RixZaWZtqndUW1OpC1cbayzHidUk=,tag:aQkT4GHdtZtzqSS0wfSMVg==,type:str]
  CLOUDFLARE_RESTIC_REPO: ENC[AES256_GCM,data:5yG7avxmdq7FJ7BjKi0K6HYUXljXdEf/66kZrqlacn4Eo02vxJV7neZFi7iFr7K8gDoBNmEFOo4a,iv:2p0N5GT7oWWQ0kpKOrJHHPoZRpbwg0xhAZs8bb1gQg4=,tag:Wh9Lp/qqpz94gGuGpvHShw==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:xSXpft7xrO3v,iv:1bOt2UwKUh8IkAS8UwPUB8uy3sWsPE93TuCKdjIsMHw=,tag:VO+p9oYtnEGVSTjnyw5xQA==,type:str]
  #ENC[AES256_GCM,data:xgTzgvy1ghYwRyRgAZtwUw==,iv:/awHSbY/I7Fv3t/PtYRXV7koPkkcbvVXFvhET7QgU6w=,tag:5vnqH1pzUNWqFytBR5FOeQ==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:1QTW2pHQXi++iw==,iv:yj824wuQuDNqk5pvtsImpQsk70kq1byUo7kZZF4FwCA=,tag:rP8TD4Wp978a4nFLj33H1A==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZlZXQ9L/r5YRsekAz/iYFaTUNg4=,iv:SA93yI6EiIla7+Aost6Y2gneZnllZgfrLljS+DAoQI0=,tag:T88Xr9WzRPBO/bQWJFTECQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WtV0mYxm8YcwjUPBj1CyWK0Zsv1pyPfGw1TntxwAy4x6ecqPFA/Ngw==,iv:26I65/yALXV3hweA2TnTiDvVjt+aCenS4ggwIh6YJts=,tag:eUcO4Xls9wlzeGgYIaxp4w==,type:str]
  #ENC[AES256_GCM,data:OqPEGlWJLHSgJj5TNQ==,iv:Qoy2vvMWRBSpfn1Nt1JGcfVfJstrb5KfdwwK4apFU3Q=,tag:HBnLQuL0MReuF2l0oBi3Mw==,type:comment]
  PLEX_TOKEN: ENC[AES256_GCM,data:++7RqctxVGV1HS5x/0+/K396SZY=,iv:Reddt5JJ6I+mfGBet+rE+Hw4UoZkx0u0jJ0oueLcrBk=,tag:tuJPRYMcP7iNmueoZ8W2pA==,type:str]
  #ENC[AES256_GCM,data:vVTPoyt7MZMn,iv:R21NBEnPwCjI1biJ4MajsuXcrXuIRLtdVU4TTNneffc=,tag:QZK8U4eYtgJF2s9MQTGfXw==,type:comment]
  NETWORK_BGP_SVC_CIDR: ENC[AES256_GCM,data:PRJ2RbynHxe2q0jXs2k=,iv:O1mZnFttNxiKtT+X/XYp0y4kFNduhGDfrL3bbl7dc2Q=,tag:+Yymz/0F67VhSpeWoBmVRA==,type:str]
  NETWORK_K8S_POD_CIDR: ENC[AES256_GCM,data:cy4xY1vqaiakmGWt,iv:TYOVDHLQZZlz4IDaOTQnLR4D4II+2hZvWw5kAnTUYLI=,tag:2UqGHv24YZR8gYmuQlq3Yg==,type:str]
  #ENC[AES256_GCM,data:ltLfNhsDwPHBjSuk6GNHnfg8,iv:66FS/8lF3GYd6GglQaccfZWHYl9TlZ6B89sQcWRp+8A=,tag:Eov8iS7IpEfNEK3Cwa58Bg==,type:comment]
  #ENC[AES256_GCM,data:7EegII1ywgnBZKvuXH6ZuFkV02gncGXY/j+UukZtegkU69w=,iv:HcqJzSaSyFPmQqB6QJnah8TIQ6gjXw1aXyuUfcwagbw=,tag:/+dvNmEMiOI9AjJKhllgZA==,type:comment]
  LB_K8S_ENDPOINT: ENC[AES256_GCM,data:qnmXhlp1AlyLTaI=,iv:5i3D4aTDsjADUMwPMyIpHss378kN1aw5wFDkBhd2fro=,tag:yAplaaQA3/u3fDkaDtJHaQ==,type:str]
  LB_GATEWAYAPI_EXTERNAL: ENC[AES256_GCM,data:SKY0jGJcJx9QdxA=,iv:1rkOLPZldtWu3N2mqHlE/HgH8C1P/AQCerWbpqlpNJU=,tag:WVkazxbqPkyQKieAap6wAw==,type:str]
  LB_GATEWAYAPI_INTERNAL: ENC[AES256_GCM,data:rdJCurKw83N/DCw=,iv:49UbSU2+Adzlod7KSe3rF9yZcUD3FmQMpg7B0mdHXsY=,tag:B6hC/KxhjmqzCU+tJzlW1w==,type:str]
  LB_LLDAP: ENC[AES256_GCM,data:5Y/bxnsx3vpukY8=,iv:Zfm/wIe9VSPcHixk/ioY3Pe+LQhrRJuNw5yzrdE/tH0=,tag:Tecj8339QlAulE2jZgRcZQ==,type:str]
  #ENC[AES256_GCM,data:DnAk892ae8Zqhbr70K9WQS9Y34UHtU3IHyZGQf8=,iv:/Rf9rPvuoYnbGFvvtMgpPWahWdl4d+kT0cX68EH7rDQ=,tag:O3euHj5I3FE+2pwL5FWfAQ==,type:comment]
  LB_KAS: ENC[AES256_GCM,data:Ss28o4qYWVp89kU=,iv:MdV5Lh0b7pDsyGEPZeyQ6UCfIEpU8usYh0gS+DqtJj8=,tag:Ix8NOShgiz/sIh9Jaddr5w==,type:str]
  LB_PLEX: ENC[AES256_GCM,data:no/aIPyAEXDdT6g=,iv:6Z17cz/u8xpKHvhZqJrdPYOpingD6KGJo9tMbYIu/J0=,tag:Qunn6dKWHTTYBgeoVSmUyw==,type:str]
  LB_K8S_GATEWAY: ENC[AES256_GCM,data:MUlDw6WS2IN5iUM=,iv:xUR9NWFJoXSjiwfLu17qOk+lyO3rfQxFPoT8u0QkHdI=,tag:l2RaYpBksOAMnxEpdewo3Q==,type:str]
  LB_HASS: ENC[AES256_GCM,data:Lhrc8cdBGzV7RJs=,iv:ML25WwoPZuxzbssrlVMYMHGRHzskJf2l8E7ny6al6yo=,tag:DUJkXM+MKrirvE/sN26vcA==,type:str]
  LB_INGRESS_EXTERNAL: ENC[AES256_GCM,data:m4E+hbiyf7qvFOU=,iv:9SgM+atVcwGpxiPJTlCGZ/8kcxpTREg8j0YAgTDYghU=,tag:/GDHk2lfIsNQVBwtycVBEQ==,type:str]
  LB_INGRESS_INTERNAL: ENC[AES256_GCM,data:Fel6dBg/uy2TpDU=,iv:3oQbkj1ljlwbV2Zq5IbRzQRGI49bSd2b/HnJ7kafYSY=,tag:drYJfEMckd+T02hIAx6Yyw==,type:str]
  #ENC[AES256_GCM,data:lcbkoGmqwE1njuep+sEYCg==,iv:gLj2lv3A7NIMghkCVdpNRj+cZBCKLDjocqAmTsWvNFQ=,tag:GXD0/TpQOiHaEdGQpfbX5Q==,type:comment]
  LB_CEPH_MONS: ENC[AES256_GCM,data:mmWh67r1H+I27fI=,iv:CUppemUufFBiVyjHDUfgOsNMOplrlnE4c29E9e7TmYs=,tag:85xrA9Ptgx/HEiNOT9WfhA==,type:str]
  LB_INGRESS_BACKUPS_BUCKET: ENC[AES256_GCM,data:yuCiZ4a4HShaqcw=,iv:wgeWqHyY7hGQ97UarDSVS5xAjWHs0GImPIRU+N/vfc0=,tag:UPYduYZ6YFKIsIjAgau0rQ==,type:str]
  LB_HYPERHDR: ENC[AES256_GCM,data:WMgV8o/2tGV97GA=,iv:sUk3mk3RZYMy6gWZX9tWualDmq4AUTfsAKNMJ9bIDB4=,tag:T4CLiGSGgbknnSIonMWgYQ==,type:str]
  LB_MQTT: ENC[AES256_GCM,data:ufayQg4W3olp0Mk=,iv:AQU4gCYBjaojhHmdPbrb7eQQ0fZ0VTxmmUBT+WoN6IU=,tag:u1d/6EJDSHKK0KnTfvAmag==,type:str]
  LB_CODER: ENC[AES256_GCM,data:/cKY5rjkWdXEmdY=,iv:GvntD4TRCnvTFGBSY5A4RdbKpLX709FshsFFsbJ1snk=,tag:HYR1UF/V23FJXxnOBfCHpw==,type:str]
  LB_FRIGATE: ENC[AES256_GCM,data:TwRDoKQsVeppKrU=,iv:R2R95gWGNS9n9Bl2nJaJU85JUaIBPsedFve70K5tVUg=,tag:KzKKn/BrnUt1qI2V9DFZaA==,type:str]
  #ENC[AES256_GCM,data:Tt0NsNN9lsda8qYsEDv9t+SIoCu3d6UKtJUOeecEMdN10oDs3e0ZwdXM,iv:ENesJu60HPC/aqSVkyA7RMQmVTp5ca0LMLbqsWR7W98=,tag:hpEUs70YRDJjHgPOyo+lXw==,type:comment]
sops:
  age:
  - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZFd3bysxT1BEUnFwS1ZJ
      RGl0UTJIYkQzdVA5V0VQSlhCbmtCRkxqcno4Ci8wSlc5VW03YUZzb1A5N0pvM3By
      SVNVYTAzbElxZTI1dEtWZWE3RVBjNTAKLS0tIElJeUc4WmtCVmZMbkQzcEdDRkZW
      VlBaU3Nxd1U4VEc0WE0ycW5vbnJkWXMKpDAZF5+I0gAFJytL2DBASA41AUbv7U6F
      H+1/K+0cl1jeLQ5V8wReG06Umg94B2IsZWOL1+e5vPUFalUSwQ83og==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T08:01:14Z"
  mac: ENC[AES256_GCM,data:avimWF+EhH5Z0RiBS0II+jDQTFghhx21M6U5Td9I65Ai1+kXGe5Te4rl55fLyJdEAYTP4phVii5ao/q0UM3BOv9Qu8Q2C2+1BEbma2hTIvbglVssttDBkP76k9j8z+1TTVNwwkwUZhp/TG5RgayYprf+6WKbR3abfMyScxne8XU=,iv:Mx3QNPZHtH0tJdD6+RhQdhBDNC44Z1WPyiWX5D8ob/4=,tag:cqYRQk1fhn8M0rJsoklNsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
