apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:FYJ/UBDPe+N/goGDgoaX,iv:ALg6VLE4hgO99rvtjaUrVRVyvYhY4VjB6yLgLE/4hV8=,tag:n9OdaLpqGa8yk2UBaHtRrg==,type:str]
  #ENC[AES256_GCM,data:CM7bUsPA6zFnDjGbbt6CwcVkWi8=,iv:NCfTuKdEwD4puAKwziFjvL703iIOS86qpGvjNh7yL/c=,tag:Zmdk6sxJ5Bj3UkNboqi29A==,type:comment]
  CLOUDFLARE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EtzD1H+y145nF+g1R9eCwuGXCWn3IGD4iO4VJNLoI2A=,iv:0rwk4Q44vHhDjkedVHugvcqjZPexDu6DirwE7n1koZc=,tag:PKaKhzMLU49AFdooM0vmxQ==,type:str]
  CLOUDFLARE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AiLFbc5uFUWogN1i1xaIiJ5vsYPYRxn/9CxxnUARt9P1bRd8FOqZpQaIGLGbf20686PTPQU3+ytdNsSWQP5t3g==,iv:2KzhijOK9kEvJCC3JcZojRz2K4yWQBnlRUy0wYUT6Vo=,tag:yR7UxvqnjDco4fOGUk9bdg==,type:str]
  CLOUDFLARE_RESTIC_REPO: ENC[AES256_GCM,data:9EbPY9iB217PCczqMyO743ggWfrojNxA3kHdp2b5a4GQM2Gf7ody67TQN7rDEvqhrMYv8I9vh2Ys,iv:GI9HtADMcfkpZwtuYOGlRQZ8m3qdeyml2rtIvRcGF1A=,tag:zXmIaqEix57pqKlxIfHIoQ==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:AWGrOLmskBmj,iv:qjs+74Awjp1INiblNoRKjudF6gIxw89KG0lNVH3X7wU=,tag:XKiHUQRp8izXEfd7qEBkyg==,type:str]
  #ENC[AES256_GCM,data:jrChJrVotwZomssx+KZM1Q==,iv:BgjAijsgpVml59UkWgm4tO8p9NUkJZ2/UB/l0BxhGik=,tag:D/Kz72jpvzSC9w9cKFr6qg==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:W9zp9EtT9irctw==,iv:fstRPGVIRzeSFAf8yYY2BbLy8OSconydjN83NWkuriA=,tag:5R7xPObqlBBeTTdgQMUeMA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o9nS1pNQhH5yV2eQKVsTFvBeV9I=,iv:62tU3/7O5cXggqVpzGngiMEQOXyKryIGR9POtHYDFpw=,tag:S+70+F+9UgsPKFa8jWCfqQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:87MRHqFo1GOMmi69mYMIq1NoGr0FRpbYP85Mb3gQg+xCGLUpyK5X/Q==,iv:pCfbe+Uyo8SRXCfbsshoKnEeWJdqBDeOSoS+4kA/GRg=,tag:2YrdUKYDQfbOB9DAEZoekg==,type:str]
  #ENC[AES256_GCM,data:NYMkXXY14e1f,iv:Qp/yHM+gPf3nKO59wNoPGN8GmQ7CYyp4cRt84aUD1rY=,tag:PJ91oDirj5phNZUImqFwXw==,type:comment]
  NETWORK_BGP_SVC_CIDR: ENC[AES256_GCM,data:J/uw3bGrlzNGyYtKULw=,iv:8TW2errzH5q5/H2GfO6u4mmyRh76qVS/213luLfWY0w=,tag:g7asd+7U4npSmw0wceNGww==,type:str]
  NETWORK_K8S_POD_CIDR: ENC[AES256_GCM,data:JRqFAAmb6XTSj+as,iv:BQr6zBiWg5M86px2m86Qj7JoUH0v+CjiyhEIoZQeaLQ=,tag:dMujTliM0bFWeTdwKiQ92g==,type:str]
  #ENC[AES256_GCM,data:E2ZVgNjoEbG2bd+pfBmRqq4I,iv:XxiY7pLy6/odZWh9LvHbIEwC3DT+wncudSQpSVrOJ4M=,tag:f2xSiqa1lObGXBm9ti1tFA==,type:comment]
  #ENC[AES256_GCM,data:ISieoYYtLFsNXv7HG4q8fMOiOY6riKzpwq6i520pyd1dQUw=,iv:cXArnXLz0kyFhCy/0cQX9+teSJuNRHto3mJhgA30hNo=,tag:uvI+rZl1HwOJhwODa1L9jg==,type:comment]
  LB_K8S_ENDPOINT: ENC[AES256_GCM,data:QnIBnQn2zSPHqR0=,iv:DbMyIUqWqUYLtGbsUtsEK6fZ/nwVOGGIixnVocH1wME=,tag:HKdxDen49Qqd8jwevatN9Q==,type:str]
  LB_GATEWAYAPI_EXTERNAL: ENC[AES256_GCM,data:UXf22JjhHrfqPOQ=,iv:SQ7xizkSj6+NipwgHRFOAw1FOxrlfR5DJjM2daP5Fxo=,tag:3s5jWHt9kuEFrz9Q6XuMEA==,type:str]
  LB_GATEWAYAPI_INTERNAL: ENC[AES256_GCM,data:LI7ZctXNTPd5HKA=,iv:vgnjRY0+ctLGcYjYAYpaMjC84dSRNtezeuJ9k/HzGdg=,tag:in7KuiNbHG9CCy8fGY5Yiw==,type:str]
  LB_LLDAP: ENC[AES256_GCM,data:LntMJWucLeSrxQc=,iv:MdHVdfcB9ZV47NM8b7NpT8X2aTSyuE2Qr0nzrZ+dVog=,tag:Yd+2TL6RJGB97bGU+k1MZQ==,type:str]
  #ENC[AES256_GCM,data:c+4z7ijYhGebsvfVvESvztNAMX3wgKKB2vHLTho=,iv:XZMHL1RgVjUjzOObEKOLRy1jc4jMB6i0eqMoUnX31aA=,tag:x5kG8Ad25yPF+YOIA/KuMg==,type:comment]
  LB_KAS: ENC[AES256_GCM,data:2YgJI2Waa7pKlx4=,iv:csEmeXqbu2Zgk8U9bBpW7Lfj2Vnr2qzCYdaXS6jwE/4=,tag:weoojQNQfzuVx7mzq0H86Q==,type:str]
  LB_PLEX: ENC[AES256_GCM,data:LhKoW9yfTlIj0jM=,iv:72QQPzu1nnxKejlMEwcabZcfRqxWboLGPJNkBV7nJg0=,tag:K1/N0btWbIGQ98Nda+FGvQ==,type:str]
  LB_K8S_GATEWAY: ENC[AES256_GCM,data:DxVkgt1VX4Spq+M=,iv:QemVLNFUzVpOS0sSTeNqgf65mMTG/M0QPavLTBkTLdM=,tag:OZqF4hlvDF/cmsSPchRe8Q==,type:str]
  LB_HASS: ENC[AES256_GCM,data:KAwyMTQmkqmzQys=,iv:fm+0AgM6iLihoqM4Sdmy59AgpeVmWxzx2qUbI//Z/DI=,tag:IM+2wmLRWq7qZoUes/KIUA==,type:str]
  LB_INGRESS_EXTERNAL: ENC[AES256_GCM,data:/k5Vp0SWJ+r6DMQ=,iv:3t392KJtWSNVX5JeJ45qqmT/SgpxLazUjZS9AFojRS8=,tag:zVeKHuPU9OOK3A8mv8OMtg==,type:str]
  LB_INGRESS_INTERNAL: ENC[AES256_GCM,data:kPygGQkNx05/Js4=,iv:ZNgwhgGEsmfEmhS8zhyFPsZ75MFUst5a1amrPowrzNo=,tag:C1H1kdmRzpLy8vMEhW5LZw==,type:str]
  #ENC[AES256_GCM,data:oDywHBTManYhmT/2z/GAZw==,iv:lv7WEXuX3hYSFfFtONnL4+yR22bQreE37YsiOvbRIBg=,tag:dHsEct0ZaJM9D42G1y13Xw==,type:comment]
  LB_CEPH_MONS: ENC[AES256_GCM,data:wAqBpsFO1jwD7oA=,iv:REulC2lrIfAuE78BxJUdfAEcLPsx79ItN/viFXO8d0s=,tag:VddDqo7YkBWpB57sYFPTyw==,type:str]
  LB_INGRESS_BACKUPS_BUCKET: ENC[AES256_GCM,data:nUYWiNzAgnWA6Fg=,iv:pNgXVm5D6vY1zzfX0VG7VxTD58OYgWEMhHA6NPn9TfM=,tag:650QiUvVl/1FBPzTGUVADw==,type:str]
  LB_HYPERHDR: ENC[AES256_GCM,data:7Yx2nw9NHa1XHzQ=,iv:Euv57QISPRQ02lom6cq2L1QZepC+AWxrK0MH/OdHF6E=,tag:u4HcGQa/vxLFZ/eJoiEreQ==,type:str]
  LB_MQTT: ENC[AES256_GCM,data:bRkyt78dQHU4rbA=,iv:kLCnQDfaeQDXuj81S+BqH7itJU83WPdZIm77TJNuVjU=,tag:bqwJDYqt3uXvUED2VgL9gw==,type:str]
  LB_CODER: ENC[AES256_GCM,data:OXTU1BDCgcBLYUs=,iv:5oLMCwr74rbLRzTddjXQrbWoqTxYqNrQjUvg7aIWKL8=,tag:inTkTOy0dsUvOBKAMusLxg==,type:str]
  LB_FRIGATE: ENC[AES256_GCM,data:/5OHzYzb2KiRocw=,iv:rrfASfhRukVwCc0pOrEiSccyaa5Gq+3Sk1Eu6XxCb6k=,tag:8MeOIt8GRJ2uHiw2oahNsA==,type:str]
  #ENC[AES256_GCM,data:lfdu4+/33hAu3n+h871HgK7DPxV/GWx9zAt1wCL16hL2Wz0Nb4tsJEPn,iv:aRqrRD5kFFdiPnIC9HcKDtg6TRuuseiX5gQYc+vndyw=,tag:HUhseijVuV/nhrrkmTzeLA==,type:comment]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZmVHUjE3T3luVlNLMllV
        OUVwZmV0V040emdIZ1kydjRSRHZwT3E4d0RjCm5RM1FLQ3JVWFpSOXZVWWpUUHpq
        ZkZLUkRqUHh6UGNqZXRXa0VQcElBNkEKLS0tIHJKQmNsUEllWlV5bjVNeHlDQllZ
        UXlzYTdZRkFvTzkwaFdYMDUvNFkvamMKooYAd/2aSFQg4N8jXRhk3Bv7jhi4Fhxm
        oj/jgCRBB9kZtwNnqp/sTVSkvv9CGNFS0x5pCrTlfBFb831ye9CPLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T02:53:17Z"
  mac: ENC[AES256_GCM,data:fIpzM3cIHu/YYieQuc+vvtmwGc0BeuaVsVxHYG13WUrFDed7Bj1B5tXzwaeedIWfa4AotIn9hJbeHecGFWVMnzeW48FL9oAxDzSK7/ztJoK45O/3ZOTgtGx1u8gD2N6j7vmIqPMO8RXh2HyOEPz/Zfqbyja/vmwb6gK40aSM0Dc=,iv:lSh8qXiJZnS8buiH/3eh3AyckW14Sl3whDZrbvRy9mw=,tag:jmu8d91r53Ql7Bs2pmweqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
