apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:tw3iXXhkeaS/j9FwgusYFd9KaHqy1Ur7l7nmWygqP9E=,iv:aZod3UPY+Pb4tEzusD5nXg8bCH/PlJZKmJsp3Lc8uwA=,tag:GOhGL8BN9XSHDcl7Zyc1Fw==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRDFITjJpcm56ZTJHeU9k
        V0J1bmxUVVdWUVNOUDRycG9qK2p4TUJOa0NBCmVEZW01ek1keUFkRmVFM29kZUFP
        MFhUMi9KK0luZkZrdUhlQmtSMUJFLzAKLS0tIElPNVp0N3BnYk5ZdExEOUxwWU5S
        NTNGZTBMSmRrbWp6KzFDaU8vdlZiQkkKCpEUBv5S15BhbWVR46lwJ2wOkmY8Rdm9
        Mfs3QZeUriNwJ0XYT1v+NWNOEhw8FC+6+4G8unwkG4HVG1h+jm5SxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T06:30:11Z"
  mac: ENC[AES256_GCM,data:9WMWDMH6mxwKzDvMOV8F/AuFNMDME5Je8b/vIyz3apoTs2mxbfAonzOzFVhlbxEHyA8D0KEc0d784EdGk/dBx5M497JbtWNc06ko+WJ6lF1wutnQyk7k1Kg89UtM6Hv8BxM4Ph8F21IFdGk29Jj2qKn3/c5xrfrn6VgA9y5P1Dc=,iv:OjCrCmF9SlYxdX7fAZsPlldQ8KQ/Qy4XEXpzE+ak6q0=,tag:ByfORL5U7TQS508ufQMM0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
