apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:IurbBnfwkxS3XPaLZshmFkGmRXKBQHr7Q/krAlKhpY8=,iv:o9OCjmb8X6tXq98zSot5uSXSEKA/rhlUZms4KCb2rJA=,tag:vE3eB38UkHxYCIAmVIMPvQ==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cWNtUnU1U05oWDl2b2lo
        Sjl1aTBXRTA2MFlud1NyTDJRY3JrWFFpN1NBCjNFbEYxN25BSURBd2dhMzFlbnJP
        Qm13MkVIUVR5UmhTUVhUSmlRckRxejQKLS0tIEd4SStZc01HYVU3eGRCVFdya1hI
        cWJxTFlKWFh4MERGQmRua3R2V0VOL3MKygFSmaWrobA+NdFhF1T2qt4rksYs7ULi
        z6pEejy3h9bxbSy5g6cAvSm8YA5bg15p6RvZM9BJN9TKOkMne8mWlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T05:59:36Z"
  mac: ENC[AES256_GCM,data:4kVgl3jiq3Oxwcr6t+MzgzDFmz7UTLMZwBeEYJqLgeJ9eXX5Uv93U4OdHc4NVWjuih6j6F82BtiZTVe/Zzd7Z7cYmI5NWrM5oRHqerjhHRsSyS+PdhjB1ciRyPhauUvCrFGgM8DByFMJX9FddWZi+zf7gVb2zcri+cSCrRb5np4=,iv:VJl2YW5OEE1YdRABKdPf2HGKmHHD7ot/rm7JzlIGAZs=,tag:XK/7tPBzrJ3FB0hwnEwIiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
