apiVersion: v1
kind: Secret
metadata:
  name: esphome-deploykey
stringData:
  id_ed25519: ENC[AES256_GCM,data:XDsWRbxYJ1U/zRqAKSWNsg5p2E/hiXO9QxgEh/GRk1Tjjqv8UzV6VBlNYglENgYdOGgyC5StBbDIE0faB+IgIrQzQ/rZcnHLfklIal8sOPQ/y1Bq+UBQFfkEL3H6DkpSvYQdZ7cTpzUeI5E4yDhlEop53oPF6B/ReYD95RZlq34uLa/0YK5fx0Lw0H+OcWM8fY8c/c4zY1Xe9Id9Al+2zPc36py9FPqviMF6X6oYMWjBI/Lo/My3BN1xd6Vt3KzJJmZjj+RXOzC30ZNfmPqYFht59ofx7rBVltK6dL85xe983LvqQ7gAbFW1ZBjH+hW9ejFU5rSwIZG65gobo3RXlIScvSark8SBLtSHYYtemqYLlEz8VBYsWtJjqS3le5/3HHNS3VfPTrS23KnEZQhR9NLzhmIzOYQHteIoZryqVCyrFHTrmB9B88r2waXz8Q00,iv:XXDv3iGnlHev2qqgCLAHkXyNHoMTjzQhbpuOP5DfZYU=,tag:F0LG7/rs5QmbR+Cciz1Ssw==,type:str]
  id_ed25519.pub: ENC[AES256_GCM,data:79z1jJEW42l1XFjKv/Ee769EMOStkUKqt+CuGxfrY3SfD6E/XBentejZWOJqDCpu09E3FTL+e+z+4CGqig7xH9yRLA4Le091IhQkoZmYhSJvRf3ZpQI=,iv:adqA6mtKBuVBh86BT3bwrKVp3PrXxEZYeB/x45tgoQs=,tag:OOohYP+WsnqnshgCIZ0Sgg==,type:str]
sops:
  age:
  - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcVBqekZuY1liNTlUMERR
      czB6TEZUZ1dKbWhZNGRjRThkSWRPejF1dnprClF2OXhxd3VIL3NIVUlQNi9mN2Uw
      SG1uL0ZpU1NDbVZvZExPWTlWOU42MmsKLS0tIE9PWXJNZktBcGsrYTJqbEQva05L
      M2VibUkySlVHRnp4L0RXSUU5blZZS1kKmEpMNeyB3HAWgxyzmtoGP6CntS++arJQ
      +wbNL5A/SeMELxQNF4rvbxTt/1NxHV9HPjwQFuldwNb2Sk9AxhaPaA==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T02:10:57Z"
  mac: ENC[AES256_GCM,data:PYdzfMWNNQ7khFrEownaIlPrVHcmqSfT1sqMEF/bkqVyJZk6ZriiagNYKf4Wjma/WXbjNA0wDoS5V9Pw7O1tIOGtiOcDnNvWrvVTHYWZ23UGfrWUkSnqNFMNdW0iwyf9BPvghn+IX8Y9Uc3YTmbhE8mzKD1rwjwl49uaZfSJE3o=,iv:SEyMHwr9mgfzyq9p2hWrmiKAhfPuBOPeq20ICW1c374=,tag:5vQNC2T/ErbaBfmg68tIIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
