# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    labels:
        app.kubernetes.io/name: lldap
type: Opaque
stringData:
    #ENC[AES256_GCM,data:g0i5pw==,iv:uTs+rgWKNtQT3f7wuygylAemLmBa5UTBEcd4kVUstkw=,tag:pOh4zZl2q65QXF9mdvmptA==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:JC653Y3gcGxeAy7CulEfGg==,iv:Seq/SU0QmnsZhuKKU3f+ZeWBD9hRSkjdrPU/ciivJsk=,tag:dPEZPGLBXcj+FnsnZUePlA==,type:str]
    #ENC[AES256_GCM,data:F3WoZpojZAA4ArIXlDYOW3suitJ82/Rhqxf99pKcOCUnjUGZIA3OrvPhQFkn8nKQilGRUaigrraqmlxikhE2HMuzRJGNy8k=,iv:7DE2faInCKwnyUhSLEQZy2QzXDdxpmiW/GnNRfQPYas=,tag:NwCuMbFWFrePKhvR0zl3zA==,type:comment]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:oWalk8b02i10RQ==,iv:rQ3jvgB/ABpQOpsB3dkofSA6tRNc/KFoa+i48daCb34=,tag:0ghhahGe7ucImGRYdrk4bg==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:WNo4k2+LUm0=,iv:OE+inBlXZomJ2ZyhBjp1kKMPRh+CBQeh6EBzj31woi0=,tag:4BoJ1abzrR7O44ONkwKs6Q==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:fwxe9eNsnoRSne7ADT/+nJLhlPUl0PFd,iv:vwXv0FeJFUxYiZXbuh5A68kBCbn7fznS9sEiYl/pHik=,tag:BjZJ5Y27cCWSJf2ncHz2fg==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:YoGNT2fe8pFnZq9AKgQqXAe3xDV74uWuERM1tPZ6znM=,iv:8yQuKefkiZ+o5XweF+FLw/InbXRDZR8Bbwx66Owco+w=,tag:z3MZ3ja0JrGmHae5N6H4ZA==,type:str]
    #ENC[AES256_GCM,data:5KX0N0CjvfnkBEW/wzfSZ5HJjzqJux8udWlclejJjH8M/nNXmJgDUFd56sHm/WscILX7eAqE2D3UqwtL4cskTrDis8hgTMYp97b+DUETvE8Xs0JlhW9Y8W9y177RKQEh4Wu/eLyy1LOR34ZAIsyD5XtW,iv:giqoSeBOLpnOtAqqbuHHjLNU+5S8KwhMZaTnm3deFhU=,tag:bpT3BgwakQc3GB6Y5nGiVg==,type:comment]
    #ENC[AES256_GCM,data:vS/3V9FrYkP2kMMcsGY=,iv:ykh0j+fQmmtDN5Vjh6BcE2L5JRMDDJlt1/24W5dlw40=,tag:KXTj6NVIyDgJQn4fZ3EOLg==,type:comment]
    #ENC[AES256_GCM,data:RWSNI/PwbpaKi2WF4/wSyh0k4MYwZ7A+iuRF,iv:+zH7vLjaeAQQMQK9Hce/Jxj08zX32x4WZamO+oWa+EI=,tag:cSPkDurrIEkBlUnvEvBMOg==,type:comment]
    #ENC[AES256_GCM,data:UpUyapB6c2Hdv9W+oV8wDbm0kJLnpp4grHUJ7Q/Ku+Td5mEIAsltfP3YPTPNXEYtoYC5aryKQKFKkGs7,iv:F135/a9tneHmOfYuN0afMZDHn+dTSBx4F/Qb36EouYs=,tag:WcgBBC+LHgidcYskzNOLcA==,type:comment]
    #ENC[AES256_GCM,data:g0rjieywM9ZurjLzv2wyKsScCYFsTWmw+g==,iv:PT+rCf5K+mBRzUkaGxJ2t0FS7QVkseEwDstzFECP5Ls=,tag:ZWHN4E58mw0YCE0ij91r1g==,type:comment]
    #ENC[AES256_GCM,data:xgNMr9qfdw/SAWFHwU2ivHkYhMcj00nZ2bn2nhdMQd5GY8+Qd1+MapcSQUxL1zOx6L4=,iv:5h0CML1RIxBxxzTnfc+ZjQjCSWJYH0gWLSmA7ez1PYo=,tag:LOnoiPrU8lpqj9Ta6piiHA==,type:comment]
    #ENC[AES256_GCM,data:Bh0ggc3h6i0DaTZzIBPAeBTz0Ij1gJtlvpWJ68P7H+FnQ/yo,iv:RL9K6UyWHoJg7VF09XqMHsqBrTe27WOT8XITQc2KiSU=,tag:eN6WK+pIOB4+ctRoHmRgKg==,type:comment]
sops:
    age:
      - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWm5tRFd0bWFrRzlra21P
            RU5QWS8rSmJ5RmZ0S0ZKeTgzenp5Z2Jjd3drClA0a0lEVUhpNnlpRTdTc1FLVHA4
            dTRKRWN6OEF2KzJqWkYrbFUyMUsrUmsKLS0tIDRUbVVHRjRVNmdQY3NPWjFmdjBS
            OFpWU0FFZG5rRHNsSFFqemNoQVJiaVEKaBPxX8Dq3tToRTaT/ob/WYQnYnk5szvD
            RGcjIZYmnsh1zvLD6fcckXG/bt7l/9JtJat1MAXbAEvkyESoV9uYhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T05:21:13Z"
    mac: ENC[AES256_GCM,data:fKNNHvHPEXSRrD1oMrF73h64vOA5GGC01hqEAICii+3SBk/j+dp8SV1t8IjNamk1eGRbkOBal3Jntm0Mx8XOXoTKlh///eVS5NwGyUYLzYKMTDs/7ZL5pO4ZFZbcIQdrL9mKR7+vxyvv1ngNSzu54RWDITuI2Xv9/MkJnc2muZQ=,iv:YoaPo9WlBBMMwz0jttHWtQm2uKWVKlFAsvaeH+N8b9k=,tag:xLg7hLxYCo6NUwQdMxEmbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
