apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:7itcuHgkNRkmMh+b,iv:t+zl7a+FCPcCfZ8IGU18c6JZDc8OkQDbm6kRwPO/bgI=,tag:HidysdqG6hf9SAKGvinhKQ==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:rjSzbcHk/y47VjfDADPClwA7ULM=,iv:QUdI/u06Eb5Wft+Qh+bHGwzgugaXOKr2zKBngkmR/G0=,tag:cILe6lSh0iglNdwScsCO5Q==,type:str]
    EXTERNAL_API_KEY: ENC[AES256_GCM,data:SFs4H21MP+2jHn8FyZlj/p0Umw54oyW9ZmBomHLbjGc=,iv:9KCVU+TbKYmiDXtehRAQO4cB8S6+fOBnTpu20PI6E+w=,tag:bDfbhl2rOFlM6f/muZZWxA==,type:str]
sops:
    age:
      - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSjQ2SWFiRlhXdnNxK1k0
            ajV6dDRZSFBub1paTGdia3Y0MkJzbUJQd1NzCjJIeXZhU1EyS0xWMEVGSUFXOG1K
            YjNXN1NOUTBnTFp0VlBIOFdqODFDQUEKLS0tIFRUb0RmTmJJNlVBVGlvb2pqVGc1
            UlA0WFpNVU8rS2lwV25pbFNOOGxQc2cKLIFTISZMZ7x7PTNSmP3az625R2wp7vdK
            phRZkz4sT5hQAmI2/Cm3aZdxSCMYHBAbXUJXee0G8Ti2ppeD6OnhfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T02:53:06Z"
    mac: ENC[AES256_GCM,data:CTRojZlnWYMfM9Jl1EltVb58BptKGPNMUpi0DeiBAeevtad3rXl8mGJ7gYV8+n450t+h/JllJnlE6mwlIVxrtVjZL6hJwaq7p1BzPepbCcoZaGFLYXR70KTXhS6YveSjXwnsT3vMnSnhVet31ik1+l0rpgVPT5jzkxrDIWkaqh4=,iv:RlONJ7KEF+b7DjUMvgGVnhcHESGOTGxa8dfjTIKzBck=,tag:4TSylYR3Wt0CvgC2Gfbf2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
