apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:RCJjP6Ju9fe0v8Rj1YLzUhEtwgYjb38kn+CutX0hG/a02vOF6Bu5/wt4D/C49i8ocxy+wckJGgXwXm4ESaf66m8TP/2MkQVeJQOnxQ1NRnGVjb/tvuAycsitzavgPL1Ly+QRy7Gqvfdbl4uTDzFaeYJ9OxySSd7gNgVkFiJXVdXWl3+GliFErcNxWTRWvLyEgTL5eIzx17FMB4rWCUG5HD568rKuT+DMS9l7jG2V1LF4Rh2T,iv:jkB3gGzwewleR67guFHLJk0v9WIqcsOORYP3ArHYvKI=,tag:nTanTqx+oClnojhC8OxCjw==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MHUwZHUrUGhGY0NCYXRv
        RlVPbkQ3OXRKTHdNR3FpRFNYQmVBSEs2ekZjCkQvelVOSVFDTGViUGFJREkwcDli
        Y2RETWVNQjZudTBhb2lBd2M3S3NLYjgKLS0tIEg5ODRZMU53ODE5WnJFOEU3Q0xq
        VmZPak9SaE1jbmVvQnZWVis0Rm9INE0KigBYX3jn9nqziYtJPlf65McPcomFhGGt
        179m/ANE0BN8HiDnyuK1W+pZH22nMMij1JgaUD7+7BTeffH3fzDbAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T06:30:11Z"
  mac: ENC[AES256_GCM,data:MZ0U+12J6y4iULG9y2LPpXTsT+aXsDxrS/mPm1nEnceGvPsM4QL6wjLdZO670MTdyN45UFXPHbj6D7ZLspDIx1LOn03ZaLJ2b7AHR6/35fvy00PNUkH88/4OTXoASeDZBw35sYRsMdXQ3OUBBckKn09HG/y0jPPpdNKsEtR7xYo=,iv:+c97jJfw3rUW256IQjS/xXWbbvM5qGKakFDadN/3BRQ=,tag:kyPtArtbo+awtt/tj2VMAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
