apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:psEaJ66JokipfhLL6+1ZJdA9QoOEKSkPevF/UeetFQ1gi2CbXIhQ42TH7QPaoQD1oNLwbNaN75ztVjRlzYNCP+j7VzSA7q1/D92zJtu0a1LubFyalAOTuGuh2w+2H8x5yzi+E1fdVegEwOTt3BEiLb5x0KqH+s2hYK0trmzqKpkOayY9rnU15dlgobFjjJqGq62Ox/S3huT/yYwSdN79xH9GwTOSubBxXoTSEfuyZWb7gR8f,iv:yl4mpl1R4E3fiOLiQKY2oys/fRB4bfMhFE9JQgHfIIo=,tag:V0ox8SEUvjaHr/Tvalf9cw==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL2ErOWdSa3g0N3lmbjIz
        cjdkY3htangxL2d0am5oVEpIdnVaY21RZmlvCnpRTEdLelZNazZuWmNOV09MR2lY
        cG94NWNqQjVET2VWNi8zVHdTb0VtUlkKLS0tIEFBcGQzampDTkl1cWZEMVdwakNO
        N2YzZ2ExQ3hnK2ZRUFYrQjc0ZWQvaEEKtTX2TZmYtT+oPb2pYxs5Gqe+wm3rdvv6
        WT+IejVP2Gzn7UZ31r1w9CVGD7Gw1VBson0qZwkqKLVDnJIr6/zhsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T05:59:00Z"
  mac: ENC[AES256_GCM,data:OgTQTBtqleKh8b5alKnp43Q5fWFNgkHlDDjY9EWtb2syYNfwF0UdizhllLi317rbDGlrlAkpFTDfkZ4cC2tkX8JCe7H/cTJ/Zf0jvFR9+v1ahHhNl2M6CYabDQXwu4BNxeFnGRP42HKegqujLuAc9+TKq4p4yD3oBNGi7AyMxOI=,iv:DFKmjU6uICyi+7lkKIHJFfaz6aUB/pq288P2JCMR+cc=,tag:EkWJSyR4ulV5d/mfCtpMUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
