---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
components:
- ../../components/namespace
- ../../components/repos/app-template
- ../../components/sops
resources:
- ./esphome/ks.yaml

# - ./frigate/ks.yaml
# - ./home-assistant/ks.yaml
# - ./hyperhdr/ks.yaml
# - ./mosquitto/ks.yaml
# - ./wyoming-whisper/ks.yaml
# - ./wyoming-piper/ks.yaml
