apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-api-keys
type: Opaque
stringData:
  #ENC[AES256_GCM,data:cwmzwPrFtJCpVpq2PI5htik=,iv:qlvilYNwAkgK/BOHhjzky8BYBzsqgHh3GfcCS7Rwa9s=,tag:4H7nCgafDaj4gAoGpAZF3g==,type:comment]
  SABNZBD__API_KEY: ENC[AES256_GCM,data:TWjQWNmc0/wAOnwf9WhpcJZE7/300isiy5roUw8UhBU=,iv:/v0XXUKxgM3xBdHMotcaDDQ59JgLJtZUhw3TBP2g5mc=,tag:qRuKlZkGEGDK5Keebc30rw==,type:str]
  #ENC[AES256_GCM,data:VJHeeJbUq+HTu56aGmiZZbA=,iv:KGDodZ/qXjuODcbQ1N9alUpY/hit3IGPc7oAn/ie81I=,tag:eu/UmrxZ3Bthtb+Lkolj0g==,type:comment]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:M23f0RpBmS5AQcqfLz+flDui29k0bcXYczn23sXxUKs=,iv:qLbkrx8Fs2xcmnTfWH651gB3bteafywlhzeiQdJYqRM=,tag:xMQEv2cFEkCcx5ON0R4Xcw==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYkx3Mm5QcUYrTWh3MHpS
        S2RsaDJid2loSi84NGROaEpoWTY0eU01UzBVCi9qU1FUVTVPWWVJOFJudjRMd2Q4
        ZXFkKzNqQWhLRmJJSVpDcXI2RFBUMk0KLS0tIDFuQUtDd0NqVWM1eGVqak5ydmZC
        ME9rR2Z4TzNSRWp6RktJV1VYZWNrOUUK/SC5H8+pcZpLy2JDkfAATgh6MtUZsXFr
        9bKXEJFozKxi/VRXye7MtTVCJSeX7aes4IrWDEF360vwTF5hLAeoWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T05:20:55Z"
  mac: ENC[AES256_GCM,data:nO7t+WcK9MeDow40L4RH2wBQbLfgJEB3BmaPzWzYSU7KQAgmdfYlxGxCumtZNE+r7xmtUiELucLPfO5YjZG/z4oTOHOHndafIgdoEvVAggqe6yN2WlUWGYYtMIspjsaWRUpDev13A3CApjoa4XN3ku9y0YRMMzC6zxg91IlVaZU=,iv:rPoouLG8UmtwQuaSqPZgcGmtkvQlTN9+fqClacRysWU=,tag:UeiTQe526fPeMH32GJ4F2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
