apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
type: Opaque
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:EKCJdoYxyosiac01l3heWRFvT8uTikdYb0g8mxarjpU=,iv:R+PZMxDfj6qU+tP1d7uHMH2N9lVZU09k0u2BxJ4KjU4=,tag:cuP27sBK6wVnBs3Z/0LVug==,type:str]
  #ENC[AES256_GCM,data:jSxysam9Igv7NPht4JiHGfQpDH1sHk3aJeyD7qxvCbZ2ahYGxObqGOO4NASzFhA0Rz+nuhO92E3RgbZzYwzNyoc=,iv:nCT0yLhOlrDUTTQ1xuAg0qYwRJ7ncqOInQ/eT1IWY8A=,tag:UHnFrHQtd4BMV0CBKRGVSw==,type:comment]
  #ENC[AES256_GCM,data:t6VUf6UlpS4ZgpsjGOC0LNJOBwvnu9EUvSQjFEw96A==,iv:P00Miy3FAM1HQHPeL+3uf0bvXuPC2JGNTVOC1lWerDc=,tag:uDqGQzw1rNXR0VSaUm0cyA==,type:comment]
  #ENC[AES256_GCM,data:SITVg3OH6Po4FMdP/Y8QXa8eGjZA5tvvx0wUW3FhvA==,iv:1dK69scBylIM7PdT1y1ikTRUeAb2EsTXXBs/elOA56Q=,tag:w8HT+kjjXF/laPPG2CaGBg==,type:comment]
  #ENC[AES256_GCM,data:7oK9MnZFbp4JzeH/udSZdS4qQsaOS9zO7KiSG3YV5m2cE/P31U1WOMWs97Fa74N9dSmhXJk=,iv:E7ZeNfBv6yPv8NSmM3wxZ+KdKE/yyBMWSMsHU2Ywcc0=,tag:rOtTlbAdBJhn8Jy9Vv+x5A==,type:comment]
  #ENC[AES256_GCM,data:FMoyX8KDU+M5yVJkIRdo84lM9YP+tR7iasYEaPVrIFL4YtboR6U=,iv:y0DzIRJbhBApTZcQgd3hDWJJH66CJgLss860nghlZSw=,tag:MsYzhhB/pmlLV+yg6IoPwQ==,type:comment]
  #ENC[AES256_GCM,data:E4cxg9sR7KayQjjdFFPQb/V6c54zrjfVQ07hQfYUCnnnOg==,iv:30ZqirVGwWtPSOoE/mQSXcrfq3n5Fan9s7i5+Yt9QxQ=,tag:mg+khLEC5bXQTMkAoA43BA==,type:comment]
  #ENC[AES256_GCM,data:e15znyBr86HWem7JH12Wu4ZN2zSIRKjsN6T5mO6S4XxowCZWavPINBODUGnu2U8tw1k/hOSDG2zIGOl52w==,iv:dI68Y+tEpb4dmpBfM5qiqbhHMT8qRpuAsxuYO5wKCtw=,tag:DGy9hbb9KqzliMorX1QaQg==,type:comment]
  #ENC[AES256_GCM,data:cokzagf2BgeTEU5cHQCRJfEk7dB3k3oIBylM,iv:TphCs+FDwU8iCiZxfOBWYw/7+CkYyw1qV+hgA3Vhyis=,tag:22kqLR7yvsrFtj0QMkyCSw==,type:comment]
  #ENC[AES256_GCM,data:h6PpqBO918ROSDIVkErJ+PS+7o51Z2LcHEKDyU/tOz+iX0cNS4A0aEtRXWg5,iv:cx3E7BnqyxQgEDWxxsmlndVJsw/oqW4w+YCeYzjrLak=,tag:H73wRLi/cMmuRF87sxVi3Q==,type:comment]
  #ENC[AES256_GCM,data:DXlxK/UUnPLx/8NCU725Dyfwgr8Bc1YK8L5tagvzuTehbsS3BQ==,iv:rAxWek7HLbkbdP1I08CJ6MvhSiw6FjuJZ+AS+sS3UjI=,tag:1vDkYWx/bIcvw3v9X6L4Jg==,type:comment]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMEc0OUw2cFdXc2t1aDRa
        WGJ0cVZmd1BiQjRjQkRFTVBYelpkUEpQZlFVCjA0a0l1SEFTQ0F4SUVrNU9qdVJL
        SjZBbGUzamx2Y1UxZ2l5NGdrR1JHYVkKLS0tIFFwVjBWaklqYXBXNEFiQXU0QWRp
        dElqM3Bxem9HWVN2bk1jUy9ZS0FpOTQKjOXDw1es7eQFViZCR9upHaTLVjkr3o9y
        zGH8qpzbi4Ks0Nr6ZtpSQtZJ3w6Mct9SnouksvzsbN5E1zCsa0sYcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T05:32:47Z"
  mac: ENC[AES256_GCM,data:DM7vkPGaFMVs6WAmKaPq5jGkBK/QjW/R9qbPWGzUaR5Onmo/CA38JjUFnZuvlKRDwFgKZS7JmZx3KZdmrdEmZGu1e6XG/IJl35r7hrMBjMQ6neJ/dsqfrhJLY8DsxPAh2LxFrvd1UTx80Na3rZDVL8E4TJLiffX0D/29wt+Kkv0=,iv:znY/9PvVr0jHfKosXcsJSrM8wdm7vB5ev7BuzklmZ9Q=,tag:6TDW4SzlxdBWhO1BYRVBjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
