apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
type: Opaque
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:VEamfxOEX1BVJQtP3n0gOCT+T7x6LOxVwd2o3FqanvE=,iv:mqpERkQoNmzZ2pgWd/D9Bp6N1H4TF2QzjSNyyl6Lr/Q=,tag:mPaxUJpwWMZGehGQ5msjYQ==,type:str]
  #ENC[AES256_GCM,data:efNq+eCigyeQok9QPjVgVKVf6z5FThab96b04ZamkQcbqJjCjaKcpWUzqWGpPqtUz/ENb6OrN998soNH8y61L3k=,iv:KvJ3haHTo4eIoV9fFXemb+lf9HWmFcpHHhj4YiXUX3U=,tag:l9qAXOZt13j0FsxrcUAGpw==,type:comment]
  #ENC[AES256_GCM,data:YX5KYpK7ZB1kr761rwdpcFKNQp+N77s/KbYz58Vzug==,iv:TzfITAqbgeprTcmXwn/PbvWuHD6TOMEqFlOqaMsCElk=,tag:DfECX9zj35RNgoDZMM/Baw==,type:comment]
  #ENC[AES256_GCM,data:NOh2sv03slntczdQLDTjMys/M6RwXqAaZeFKJdPeOw==,iv:UhqmFzy4mBiQWlzJw5R0WtqhD1pqxWEbH2DafoBHhyk=,tag:C1xV7G958pT5m7ktlWOweQ==,type:comment]
  #ENC[AES256_GCM,data:BbGijLDo+wGzYEget6vhxHKUxh4iknwwDJisDmfZrun6yPsc6kBSK/AFf/MBQQxEqEejpds=,iv:3s9TfNmwIYwPBXCsEdWRpWUPG/knTrz299T1UatuuHU=,tag:gUYZ96h6UW2E27Q+gYNEQg==,type:comment]
  #ENC[AES256_GCM,data:XBzH72UMHr9spjWo8pSGGObC6GA+P+ld4qgz5usemjNF9RRHKeo=,iv:RV3FieKkAJVwGINdGW5nD9NWrvslnBLeJZMHV/ULy58=,tag:ZwZr9rMhx75nF2DZWPhv7Q==,type:comment]
  #ENC[AES256_GCM,data:Q2KTibN8s53I0DSQqJ8ak2nwkQmsreUsb+NSuaLVxNJjQw==,iv:B6xX3WtXk2A+Yv1FnUo8U46ijsLtclF1pbpYZv9J8mw=,tag:ArGnnWF5SEIB9GmLY6zA4w==,type:comment]
  #ENC[AES256_GCM,data:jimbJFbYlmr3KIFX0mzCuFbl+D46ruq085/qbyzPLZF8IU59ByhTDqsYbLE/jLZQxaZnU6JaBjHERa/K4w==,iv:s2l7jLD8EOrXxZ1A6IeWOYaSGQfQO8F8981UNRhAbJg=,tag:5GL/ZTavkyTXLbLG3Vo9nw==,type:comment]
  #ENC[AES256_GCM,data:hbIyyOfOB5zb0+FTmMVVh8TJOarw2xU9S4Dl,iv:cnwGFKmup+Y00XH+AL68jdjV3heE7pMQqZi3S1Lw6q4=,tag:1n6HbCI0of+RHKtbraZVVA==,type:comment]
  #ENC[AES256_GCM,data:sQOLRNLIExUNcca6El/JjlZq6HxEilEoqu3OzwycFpKPhT1p9RIPAZFLA4lV,iv:D9dQN3lQhUmHH4BqcXZxLSdok/IH5FsPY7nh9dlaK+U=,tag:PC5wYsVL4yAqPi+XGWZzaw==,type:comment]
  #ENC[AES256_GCM,data:dd5yhAigmjNvTl8c289Nmu1ZYeGANKhx9myAzoW6cKYk6nrKZw==,iv:PYRBFeI/+CXaYxlg5+3ILQHxxaDXHPMzJiQgj7cJJQM=,tag:FlQjyFB1XffBKwLW8K+0wg==,type:comment]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnd05RbmE1aUVqdHNubXJ6
        RUFzdWhoanNBRFYrOHZnUTNWbkhrdXhzemkwCmZLRVF0NnZ6dHJZKzhKTHVFYVIr
        L1h1ZFh5UmdOcXc2end5NGlHZmJVNUUKLS0tIDd1U0xXOHdJVWlkeTdIa0gwUW5O
        WEtiMVNMVWgvbEYycStTemZXQXVIcjgKPRDldIh0fGKz96UZ13nbTe4GnZyiGhK2
        aHp86DCk/4hSHUlDekf/cetakgEN2Cy8hQkpjDB6Mc7D0cW/y1DWPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T05:41:07Z"
  mac: ENC[AES256_GCM,data:7kFrqpqGH8voCaCGA0hzcwLUueVjqwo37n+E2eAj15jvV0XMJBAviniqfkklw/ccbfhpQNihAdra6fDdM+L6dzHxwG78mgu05+26HR/jvMeSXIxnQAPf5Q33gI06Of9ZQRjk+tiP1Rgz4+mdwlTzHEtoEAGfeyZ5SQEmOcVj1VA=,iv:+jVycyIeGlF1UZhI+CRwIWj6VZJSHp2rV+4BqJpESiA=,tag:xa+5vOWt+NNl3KaimW1Peg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
