apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
type: Opaque
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:MtUYlNaVFeMDUNeuBbCOEOMplq5eobYUDq7ucVT92k0=,iv:3KRZZ/roOCizJ4pC9+zgBa6PZYvvrkwPLFkrqBJOtr0=,tag:eNibZpIGPK+6Jc5JYCV9aw==,type:str]
  #ENC[AES256_GCM,data:J6LQKw1TJT3LC/YynAIKqNmSfH0CPUx3hJ6vO1qh4Gk1oRDhHMAB9uqle6CAZbIppY7k4gvsprY65dM/zlwxe9o=,iv:An961IcW370gJ3jrkb/S7HlFzptbsBDRYHQzceNR8Bc=,tag:lEqiSV3xhGgDyY93jub2AQ==,type:comment]
  #ENC[AES256_GCM,data:hg6sIODDL92UsUpOtWRf0mKhZUy38/xbINC9S4c1jg==,iv:6iTFQRmFahQFQJdUJgJhRjZWMr7UbeMz+nlJ+6BlADA=,tag:obISBlhnkoNI1/VAp3ZGcQ==,type:comment]
  #ENC[AES256_GCM,data:eKFMIZcjVURULQu7VNyFd6Ec99+VPTRcpRwwio/50Q==,iv:e3Z+GRjyfZW1a7FOLjzdlsJItEqC9BN1G635pzwKCaI=,tag:24422aoJicEBobDIBoI7Ww==,type:comment]
  #ENC[AES256_GCM,data:bni7bN4v3U6D+Hhk+glT/EmmUFGmQKtCiTQSx3HBV5x0cZJ5ypilOrXz9kVT/mZWhrESElA=,iv:jT5YnVBSE5gnwawYSpc3TSdrvaQOGkl7uvHH8NJzKrc=,tag:TkX3YpFBQRSquaEi11XBUg==,type:comment]
  #ENC[AES256_GCM,data:4wczw7jmJlpp4ctmzrfVCC1XqHZXDBdVZdwFX3Opnv9w4xKaxJA=,iv:lUzs47BA52r2V17lFYYb96NzToW9URA8oPgOn2hxYCM=,tag:cAw6ttOaFZZ6tSND8C1i+w==,type:comment]
  #ENC[AES256_GCM,data:pZrYXWmqsw1zC5i5SgFAI8FkuSasK90BwZG7eIWz4Ehp0w==,iv:i2zJpba0QaTAFny4dKIM3T8vIxNZbNUUU8JK29vzp2Q=,tag:YzrcjyT4yr/H06OjJTR2fg==,type:comment]
  #ENC[AES256_GCM,data:aCEAOGNCdGLW7HDaRx0jZnSmlrXvSG4TfHg1r8mif6af8Sab0ijpdG2iE7AdxC38A07yA6xb2hkNFXXgEA==,iv:nqN2AYRHhhOxO5BltV+Uj+lOUxtjeu0ZK2/OUNkqLrI=,tag:qbpYrmIL2oowWotyT43fEw==,type:comment]
  #ENC[AES256_GCM,data:u7wFkvS1CM4xxFhsuvw33jVN0r3OLxpQtCs/,iv:MrepbfMgykt23n/s/3j7nBKii8IzQdhxshu3R0DgtQA=,tag:VM2s0OlglvhiJyrzTn0d0g==,type:comment]
  #ENC[AES256_GCM,data:v9zmr2A+S/YdKwQV+lw9uhBU8f8yaRh1RJhehKtgqnNJ1ieBneIVR/TL1s6U,iv:4+iaoShUvOo7Sv118P0SR1napHrx93k64SS8KGHACUI=,tag:573vVi9UAyuPWtZPYPi92Q==,type:comment]
  #ENC[AES256_GCM,data:2JwLuS59qpXMRoTw+qm7k4K9VOIIFUQ39JpMjH0JuCAjgz/oRQ==,iv:UHxIMvRC8T7M5ijcNqz3a4Z8sUfDYZ/YnWpu9JxgcHs=,tag:U7zxQpneTzwgQbdvMvX/zw==,type:comment]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bFozNy9udWtPM1FMb1c0
        V29wYVpIa2QwbHZ2R2xzU0hmRDYySVd2SjFFCmplU0pHU0NXN1h5VnJnWFhlQktj
        V0Y5WTk0ZUJ3ekNvbDJsL3lWNFdmMDgKLS0tIHdjYjNZd09ESjk5MnZ3a3ZTNllP
        U29ha29yTVlEUWhaZWdhdXBwcXFyQUUKTAJSzvdazycj/JLsNR2kGZZaXirfacyw
        6uq9PGgpKhHt5n099yh9f/xzAeWxKvxo7iJRBkaIJ+T/Fcm+8RyUWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T05:36:02Z"
  mac: ENC[AES256_GCM,data:gZi2FrhoTcprRZJMCQMcQYDQMZoSp0sFeRe1dPwVLLPXyS6MhDxWnBkdxOIOMpODXFo19NtWHclESXzgEuoz9nv5TUz0IccpXfeT8A/5K+A/m5Nu0mSzsvqIRRVOOJznV+hd0QwMB98HWq4r3Y+HLaO2pXmkpkpuFoGZiSVz+JQ=,iv:z/uEhYYH8JrQMbS3hEtipCrSwek9x74LnR/4UDMANKE=,tag:X8BnQZcb210OyFisls0isg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
