apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:meCtiJeOBaHmSAqeB1h8hVHSJaD2AJbuvmf7Mijh+vB4tC0loSaMmA==,iv:zIYNF15IwM072LslFSd906awzBETRGMycFZagjt+88A=,tag:H6aX6ysDUqZnTCPFqEl1cA==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dGZSMks4VVByYklId3ky
        QlpzVk82YkpQMjl5YXp0QlVOYis5dzE5eWdFCjFFTzBwclUwbUFSYjN2bGxyc1Jo
        SmZ0NThHb1pxYkMyMjdyMExkdUN6WG8KLS0tIDRFQlpDb3Zsdit0V0ZmUTU0TWtm
        aTBtUENmQWs2SFd4U2JOVHhnblRhV0UKCYpoFCGMYeN4B5yaFKFRdUJ8CFbBgZ91
        0S+Y4iJG+tnE2wZN8xH378CB3RrCF6PcxmnESiSdT5D0/VGWLj9FUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T06:30:11Z"
  mac: ENC[AES256_GCM,data:cwowwxYdQNk9WWvd8eDabuHH1Ww1UBuLgbaH+ue+n8tkhm5S+bGUj7loOvdYP7TNV8hmbLElamC8cXdlEKn0Sk9f8ur4cX8cVgvZXy2DohnAxuk5/TmU8oHlxeeDYG2VPAvH4HnUZo+wjXH9T6Wyh64A/Uj9s6B98F7Z/xKgViI=,iv:QKeYcQmBlMvZc9HlSiNPwatXRTQoWGWuoLcKO4vRtbk=,tag:OCc1ING8pUh1c4A89ANSAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
