---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-assistant-secret
    template:
      data:
        smartthings_api_key: "{{ .smartthings_api_key }}"
        SECRET_EXTERNAL_URL: "{{ .SECRET_EXTERNAL_URL }}"
        SECRET_TRUSTED_PROXIES_1: "{{ .SECRET_TRUSTED_PROXIES_1 }}"
        SECRET_HARDWARE_DOMAIN: "{{ .SECRET_HARDWARE_DOMAIN }}"
        SECRET_ZONE_HOME_HOUSE_NUMBER: "{{ .SECRET_ZONE_HOME_HOUSE_NUMBER }}"
        SECRET_ZONE_HOME_POSTAL_CODE: "{{ .SECRET_ZONE_HOME_POSTAL_CODE }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .SECRET_ZONE_HOME_ELEVATION }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .SECRET_ZONE_HOME_LATITUDE }}"
        SECRET_ZONE_HOME_LONGITUDE: "{{ .SECRET_ZONE_HOME_LONGITUDE }}"
        SECRET_ZONE_WORK_LATITUDE: "{{ .SECRET_ZONE_WORK_LATITUDE }}"
        SECRET_ZONE_WORK_LONGITUDE: "{{ .SECRET_ZONE_WORK_LONGITUDE }}"
        SECRET_NEST_PROJECT_ID: "{{ .SECRET_NEST_PROJECT_ID }}"
        SECRET_NEST_CLIENT_ID: "{{ .SECRET_NEST_CLIENT_ID }}"
        SECRET_NEST_CLIENT_SECRET: "{{ .SECRET_NEST_CLIENT_SECRET }}"
        SECRET_NEST_SUBSCRIBER_ID: "{{ .SECRET_NEST_SUBSCRIBER_ID }}"
  dataFrom:
  - extract:
      key: home-assistant
