apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: home-assistant-secrets
stringData:
  #
  #ENC[AES256_GCM,data:DBRCN1VdMdlM6HaPrASh5Tkat6wcMgmlNZc=,iv:8DxTuIkVVQUeLzzHsudhCHV88dxO8puZUvFIpts/FxQ=,tag:csZWue1BrhfudPhuSdF3WQ==,type:comment]
  #ENC[AES256_GCM,data:ny6YDwHVXM3shewJC29zghxwLGQfnofc9BFyxAuX6BEu,iv:KbkY2P4ex2nOyQggloS1EJ/8/PjUHVjBK8dpAojJNfI=,tag:KjC63m/tP82HKivz13Kx7w==,type:comment]
  SECRET_EXTERNAL_URL: ENC[AES256_GCM,data:6iIKHNXHoE80jSS5bdYssiZtC0ZczlXJfyrDVQ==,iv:cYn0VpDf1Bcih+8Dhgm0ETYGhkpdoy1536xWooUCGiM=,tag:5cOrszljx6ysR7qfDX+nmg==,type:str]
  SECRET_TRUSTED_PROXIES_1: ENC[AES256_GCM,data:kj21D1nLTtOTdQ==,iv:qT3k0RfRhQHCvZseV0ROMQ150J5eFmdRmtksq4fkCy0=,tag:26iq+hnsFbVBwXIKmhhyxw==,type:str]
  #
  SECRET_HARDWARE_DOMAIN: ENC[AES256_GCM,data:anrUfGgub3GxHCzDvcYi,iv:pLH2egYIKDAM2usljeqBHR8jtfZL4puBvCzoaEL9rXk=,tag:YLPRMiIhDaRD4yATiZICyw==,type:str]
  #
  #ENC[AES256_GCM,data:nim4/Jl9tyRAuHBSX1t/F7hS20wRfRFYmOkto1o=,iv:7WM1alzlRw/wqNP8XDYetpPmBuaUJEOgan0VX814Qw8=,tag:Rs5vdhT6Mh1wD1ePU9EngQ==,type:comment]
  #
  SECRET_ZONE_HOME_HOUSE_NUMBER: ENC[AES256_GCM,data:jcpIuNk=,iv:liAX4cZsnqs8SdM5O7M1Z58unAfn66Y2p5qO9ofK8cU=,tag:V8fTrIpu/+t0PhUUXlcRpA==,type:str]
  SECRET_ZONE_HOME_POSTAL_CODE: ENC[AES256_GCM,data:EA3v7bg=,iv:p4YeH9J1czvRkivhdLq/RxsJ3Li45k/uRpqwTIOw5y4=,tag:uqjaIYAnTwZQA44N7OKV0A==,type:str]
  SECRET_ZONE_HOME_ELEVATION: ENC[AES256_GCM,data:s/4=,iv:GM5JRd0wFGxajlCsdVCilWaD8aBvGwF2O6azyQgp9cE=,tag:AdsYr4OUWQEbEzS3nRGnzQ==,type:str]
  SECRET_ZONE_HOME_LATITUDE: ENC[AES256_GCM,data:e5UpbcEZ6sjnFBZcfyE2ZiRZ,iv:LAzi6Hw/ZP2+v3Q2Afs/cWu86SArXe7tiJuZH4sbBNA=,tag:TcwsrJSYuJgF1OEWFVIsTQ==,type:str]
  SECRET_ZONE_HOME_LONGITUDE: ENC[AES256_GCM,data:isdd10HvmsIeh/oVqKRKoEqT,iv:/q1b/UzLHw15cqN+L3UtWyeBMi3kqHtSG2Oxt2XWdF4=,tag:MBv/A4onPGDe1sptuHzDvQ==,type:str]
  SECRET_ZONE_WORK_LATITUDE: ENC[AES256_GCM,data:GQKjfoKgxkc7eR3i1j5Uyk0=,iv:s6lJUQucYrTsHMxD3LQ2DHcCT1mOhdAPIOhaagw9Eag=,tag:3I3hc1YNemVxjACQtvXTng==,type:str]
  SECRET_ZONE_WORK_LONGITUDE: ENC[AES256_GCM,data:PsD5ore/0iNdgevWwfaha/9VZw==,iv:dYG9LWKbNvhSzEDsH9wJgpIPjmC9X4SiSOphStr4Prw=,tag:hxk0Xfhiv+nHVVvBISwaGw==,type:str]
  #
  SECRET_NEST_PROJECT_ID: ENC[AES256_GCM,data:YR2zeN4HCxf5p1Xp1guO8DTkMzzB/n1kCBZl3bHP/zM4sGBI,iv:8lbXwqmvX58Q+Ce0FNSPDK6RPOHZfc1XG9aQPIniDNQ=,tag:uVxOuc+ynu6Xnt8+ubIL8Q==,type:str]
  SECRET_NEST_CLIENT_ID: ENC[AES256_GCM,data:Pa6zc6dohTUwIbLo11h4LvCuHh1wfdQrpNHEG8Vp4uNge6Sh2WubK9rFHkgAgvGgMSnDfrbawqzzP46zWBlojXLYMOBGimuU,iv:77nOraqPYkVpp1eqkt2vuURYaRzQOprIhfVZEFb19mg=,tag:qMrz3xu1h2RSQjetL4WU+A==,type:str]
  SECRET_NEST_CLIENT_SECRET: ENC[AES256_GCM,data:CV0FCl3D/7x3q5IAD/p5wzisCBab+UqznjCdy5zBk7c3IIA=,iv:69MmjHGSMjCSGw9MxU4EjddpOr6T20BI6UEf/NdRrf4=,tag:rBQ0SZnQlxYxUeyoabtuDw==,type:str]
  SECRET_NEST_SUBSCRIBER_ID: ENC[AES256_GCM,data:GkFknyFncGBR/6HAyCu0CZX6xRX4LcgiOMZjB9EIMcLlXQGsQdWMeySLm5yTPAg/Ptp2n/W0/hOUfzqFLPvZ2nhQKgkc,iv:aG3a+qux4G1V26+3xN11aEI0s7vFqJBCU2FapIMpOvE=,tag:/45JmaXV3r0UQ46ODTFh8Q==,type:str]
  #
  #ENC[AES256_GCM,data:f5F/o/7iY6i/ymW5dwV+lgtqMSrtxsGGXZ6NfAD8U5Pdwu/y,iv:8Fv/SABdfq9A56M4XQNj5hbUyETdQRpTCE1SgddnfDw=,tag:TXChmr7jKiAkg3Q8JK2sdw==,type:comment]
  #ENC[AES256_GCM,data:nOU2yuJcDENyfnZoTX5nyf2TIVQxQ1PhVMLuYS2JxK56t1tCIByqSQ==,iv:yyXaJz/EJaWi9IhZib+3S87W3Axmj0AKUZZj8pAo5w4=,tag:wEgvQq6fZQTLqCpOW23u7g==,type:comment]
  #
  #ENC[AES256_GCM,data:TKeSOBBS8jItNwUehp6d28S0ywsFnc6hmiKc5GWfDA==,iv:G0kyNW6uBZ3vcoiSNFNIHHTGeIYuSrT76N8yJW+30Ek=,tag:N3nvgB2eCc5p35Kk54IxrA==,type:comment]
  #ENC[AES256_GCM,data:5opBrDx58mvGRO23pOQOzGucwMvwdq646yi5BYyyt2RHApU=,iv:6q+bBhiyB9qVh/VMxYUGoxMzeAZye6ga14CtMlik24k=,tag:9lJ9bbtZlXL5IRPXlbzhhA==,type:comment]
  #
  #ENC[AES256_GCM,data:aanM3qP4zVg4bkHflxxbJzsVpN6pLSLGIlrcUDzhnQ==,iv:icEV16itrSSjDrkPdQM1vxg0c6BD6S2Mjkb3+xwJ5Vk=,tag:70IwWcRVUTpM48s44+4qGg==,type:comment]
  #ENC[AES256_GCM,data:dA/TQBAOckQ212hJ1EfG8kNLb6qPANSfZuYaOj3hZcKRmnBN+oxt41K4XQ==,iv:sDKSqxmBjlv0X8QcCemiGMjUCUfPz6T/luAigHNrDcc=,tag:eSrDqFgcTeNtQ7bmOb1zmA==,type:comment]
  #ENC[AES256_GCM,data:eujWW136LdNKGUDspgJDiXwt1Nd8PpoUZC+KgdLGjK/HyQ==,iv:zcxSl4t0nbLboTW7Ozsvr2fzhLQ7fgeJWtZozmnzX3k=,tag:qeGihlrzVaqdWLhr4leoIA==,type:comment]
  #
  #ENC[AES256_GCM,data:A+Fz0rD0ZNmTiOvO1sTVRCYr9KGcPguv,iv:qgJWdoVRDRa5aEApTAWOWhb0YqalT2/8VnDLt0kRZFg=,tag:qLV+KTmCmBaWm1Ezt+ZqVQ==,type:comment]
  #
  #ENC[AES256_GCM,data:TiOF2XsZw5ICVtt05qmoXi2DLM/8pq+qj689napm7fU=,iv:dGZbFOfJ9AAEqIqphO5N/nYZqGjPf8MP2uPXTQbtKcg=,tag:Rs6PQdmJKOT8raIhQSIwDg==,type:comment]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbVBvU2xxSXNhY1FuZitH
        cWtFdXNzMHBWZVBPamFnNHRmVE1rNzhVK0dvCnpiVkF5REsxU1ROZ0wxZVp4eDBP
        NVZzUnpWMHZOVmxFR1NYdzg3eG43MU0KLS0tIFVJMDYrVm5xOGRrS3JVN2svWG45
        cThUcXdqNzhXcHIxSW9aUU16KzRBZFEKwejqm+8hTFybC6U+lcLonsUOCoLJHA+I
        Dt1/IKKs7hSm5OD/fLWzCet8TljrPdODNYP+4FblpKr7BkqHv/8r4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T20:57:32Z"
  mac: ENC[AES256_GCM,data:MO0xjd4Mdk+bkRavPD4D/Yphozkk/1geItqL7wdoh7GQffBwB6V3iao+QFXOVYZevIesaykvs0EH4+LsCiLrHjuOWBUlX+3AjYeNzcbE//qtsNNTNKp+LlL0jr6ghWiW8kjYfRwYkfBgqC1E982CWX9VqdbLwGNE82sHrQdmVBA=,iv:eKUnz77a1T6iCWN8e3VQVTRApk6e3AOgvtNWP8qDzSk=,tag:oRq6IcAi7KeQWe4UsLTOPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
