apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: home-assistant-secrets
stringData:
  #
  #ENC[AES256_GCM,data:fHvIUICpY7/hzZpKga7AgroQQJ5zCteDC/o=,iv:2BmZ7auCb8o4gKq7cYvC4X0Zk7l21jZYb+jVuuxUT/s=,tag:IjCmw+hTf2cppOTrBQMxnQ==,type:comment]
  #ENC[AES256_GCM,data:BjrM0YqSdnh89ZILIDT1o50jWagr+pTiyw6JZZ4DUyGZ,iv:4Q4Yv8XW0EyiS9zzbzlNICYuRJga3cz14yq4p1O0fGU=,tag:hrM59p0Sqi9dwyDjBfOPEw==,type:comment]
  SECRET_EXTERNAL_URL: ENC[AES256_GCM,data:Hqy7J4njP1mGW92PKHPEoCwYEjBg5U3YwvIZ8w==,iv:bU3OOFpakCQ4dF/43+M10IdFgbMeCnCYRdO5txmgqEI=,tag:yUSM4PyGBmZtmf+kTWyz2A==,type:str]
  SECRET_TRUSTED_PROXIES_1: ENC[AES256_GCM,data:S/ByE/AjY51LqA==,iv:VuRWxByavzdFwqpe0XTH34eTVAadw7XxVcWfn8Pi3Rs=,tag:BGzc+3gH68l5eRVVGimH+w==,type:str]
  #
  SECRET_HARDWARE_DOMAIN: ENC[AES256_GCM,data:mKMwFL37XL0ADQCn+Z/g,iv:FatrnBHjCVCmoJh1AYrbp5zsPePGeGqn7Sw3WG1yk/4=,tag:KiSZn99/uKZY711jUD/y+A==,type:str]
  #
  #ENC[AES256_GCM,data:AkyCxLRwPKByhu1HXYEiKRvtkLkLgJKX5zC09oI=,iv:YDD/XWok/SVWTCOPEB/mMugUWlQLqAjqu3Zs5j3yNuE=,tag:JZAO6eBMwt0cEek+MwWPUg==,type:comment]
  #
  SECRET_ZONE_HOME_HOUSE_NUMBER: ENC[AES256_GCM,data:4O7bDdw=,iv:LaMZNZN9hvD/+qQmSs8k5Izx4y8IGCXmXJzNFlaUydg=,tag:lDP0fxibdRjTV/v238JY0Q==,type:str]
  SECRET_ZONE_HOME_POSTAL_CODE: ENC[AES256_GCM,data:jAII6aU=,iv:gumVzWhbj/0RINUzQoiiAyTr7Cc6LHeXUz+3v8qZ2rA=,tag:vP/lXiNnlJha4GAf5UlZxg==,type:str]
  SECRET_ZONE_HOME_ELEVATION: ENC[AES256_GCM,data:rpU=,iv:kHYELtA6AEkgwIE7R6Rw5ytjImo0CLOFHKRwdv2NXBc=,tag:V/TRQoBW0KC1PBgclJZ8KA==,type:str]
  SECRET_ZONE_HOME_LATITUDE: ENC[AES256_GCM,data:x3h7n9dhqG0sfS0Cp6AFy6kM,iv:Hz7840/v8XelESETmm0Gd7ay2s3tlPbD1HxmL9L0zlo=,tag:+vq48V3XaZqobntDB3F2eg==,type:str]
  SECRET_ZONE_HOME_LONGITUDE: ENC[AES256_GCM,data:tCQOUhAioIfCg1Rf+LzRYveD,iv:DWIxAIsyoDabCbfysuGw8jFsk2qzcLLfNJG0Pldmryc=,tag:NAZRUB9JFHyfGIMVboCEzg==,type:str]
  SECRET_ZONE_WORK_LATITUDE: ENC[AES256_GCM,data:cM4m7a3BZn277X+gxWRraqE=,iv:9U2TfOIHyGOjXFPq3+w/qUjbdfmHvEp0Aujhv6Pb0G0=,tag:egHLv7xsSd159NJFs91ceA==,type:str]
  SECRET_ZONE_WORK_LONGITUDE: ENC[AES256_GCM,data:H7/zGAKO/YyqCOVat8oOWMvUVw==,iv:84/7+u86x33CEq1mbl9bVHdKks6oXCZk/P/PsbupEH0=,tag:VQGH1tbkunp9Hyqj6WyP4Q==,type:str]
  #
  SECRET_NEST_PROJECT_ID: ENC[AES256_GCM,data:zgJ3/7aK43tZno119pbWko4BZBfeUYiZcufUZYNbZ7Emjkc0,iv:CFRE8zZnfab12RFUalPXQezBHylgT29eEni4pVJBrbo=,tag:09NqWFXVJ5rGG+nbtgxiRg==,type:str]
  SECRET_NEST_CLIENT_ID: ENC[AES256_GCM,data:ZOC1OWKhaoTz8cyBLgUnXXYkDJcGV3uNpdBfRIqjvxQ3a3gZNKugRZggUkDv4WdwNmZsR0DXSTDoFTy98svMXVWfz6DhYqfz,iv:Se22cnEuoPYKXXy9x3GA7XuOiBEXk0qSvkraUhMhWms=,tag:2GM+FD00NQGzjUKJJGUNog==,type:str]
  SECRET_NEST_CLIENT_SECRET: ENC[AES256_GCM,data:6fiQcxklK7uZFCMaOr8wfv6aokhUUVc5R4vcfxzqVDHoBKw=,iv:+CLzGcGQvCbJE1hza4jZPVT2ogCWw1SM8iKVO7tXZ4Y=,tag:sktnhUqnhzuWY2TtjVVVTA==,type:str]
  SECRET_NEST_SUBSCRIBER_ID: ENC[AES256_GCM,data:+SjtuvqfeCvEtq4yffuZEmUzxQVNTZIfD4ob/trgO8ffLRQmn8hmVQtxVB8Bx1TD34SHQ6L9NmKreHIUecxs8uTaUyPt,iv:85GrOZ64Iqb2sSo82AzAXFOVQUKOL2VC3k+ui1RLpxg=,tag:4zcm32eYrMK0QOLPmA1TQA==,type:str]
  #
  #ENC[AES256_GCM,data:wE/9jb7C260wiPV07CF+DYLK7kaX6U1PTl1K++uvexRt7WIg,iv:0VfLzn50FUTNo7Seg2rNi3HU0bzIjHOuZ4ecAio5ctU=,tag:CbHIBax3wC23wM1f9NpeeA==,type:comment]
  #ENC[AES256_GCM,data:p6XHkpQvLBppvKgXl1kCjO1Ff5Pm5SbwTHwwOaFiJnEVBqHAWKD/vA==,iv:2AZcB+jTG03Qbs1MwyyXKS0Qodmzdphda9w+tSvZbi4=,tag:gj3htEokkIs3+86pXX+kNw==,type:comment]
  #
  #ENC[AES256_GCM,data:CgeXF9fBOptU1UDYJG0oUy5UVTyS4AvO0giD3oY6Rw==,iv:i68xjbWuuLpDtqyamliaOPylg62yhhUmk1qE3fHkvPs=,tag:CmwhNbSmwrOKf25jfJa6aw==,type:comment]
  #ENC[AES256_GCM,data:DX0/py24ogazIJzNPTO284iOQz/+ga+T1YAqRyFtRLkI624=,iv:dbAG4gaGgAF8LZ8UwURdtGRUhoJwyfZJ81xqU8tuGJw=,tag:Dq9xPHalziicT+SL3Pdifw==,type:comment]
  #
  #ENC[AES256_GCM,data:eCqb3ULPeQBYXQIfePWcqJZgf3Ateo/KpP9vE9B5gA==,iv:H1gt/XqZZE3mQrgobYX1mrSnDwpWJ0vxZ7h3I1h32yk=,tag:WM8oZBvhjzrC/SAHPlz5nw==,type:comment]
  #ENC[AES256_GCM,data:Due7cCidJY0Rhzgv1tZiZdQ+ZHQDGAGOI7rKIUAieEziw3LgubFW621Ecg==,iv:zggEydoDOIRxGYCEzPA4iGf5I45bFGhMDKvGXQ9MfgU=,tag:mAuJa7eU75iQcG7vES6evg==,type:comment]
  #ENC[AES256_GCM,data:c9GT4cwWKyC2YHpKj5DNFv5476gL1Iqc1d4gGW+ds84YFA==,iv:8Jj8PsxN8dwU5LgfuyQtxWQ/xDb8THjh0E3T6+XcDZ4=,tag:/BWJ9qTtNts7xFKISc0Xmw==,type:comment]
  #
  #ENC[AES256_GCM,data:AwC9m5KwZsiPjc7hH1iuCEgx73aB6HHx,iv:X93ODbmEYucvR+iVjutcQGgKMrr8A0pEbcrrX5anWOk=,tag:rvoxuJFxK/EyJgMgIQ90gw==,type:comment]
  #
  #ENC[AES256_GCM,data:hfd3nyTKCBIMWK5eobC1CDZ4QhsEmSzcmXdYt+D/y70=,iv:3KvZsu4P5F2QVXxbFT8hcM7lW59GCgkvTGIlKzDl5v4=,tag:hpWmnuzri+u6BLoaBh4ijg==,type:comment]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YlZkMHB5YVVkdS9ublV5
        NFNCbWFBSzYvREF2Nk9CLy9WSWFxeUhIRWtzCmNWZjJyK3VlSmRCaWVXTnhMZzFG
        ckYwczFSbE1zUm92Vk1YeW9kQWx1dTQKLS0tIEJqenZhRGVINExGeXJEU0kzQ0ln
        RUJKZGZBbFpCNEY4dWgyNW1lRHp4YmsKhHZgOM30ez4jbsckkdft6oFvHgn0sLUA
        5tfVujM40yEoC82J2nsnK9jAUBRHqESxN9pnBkceei0gx2i3NDqWdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T20:22:03Z"
  mac: ENC[AES256_GCM,data:5907nmB+7xcobc97H1qtFNWh7KhssDxJiUzF0CC3s5EaJo97Gt3iA03KbfcnsAq3Q5OTV2DNTBL4esDYqAQPZPVLiaYuI1HjrPbxDpbIM/t9/py16l0ZO0ip/76LjidNaA8i7hJEGOGn8mKaPMH7mup/17ydj5QMFMoo/Eu7+KE=,iv:O6WVipwFkb3VSlFYnmxg1KdU1Fix1Pr26plbp3UCGRA=,tag:IVIUivtbVUX6uJDqezgIsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
