apiVersion: v1
kind: Secret
metadata:
  name: home-assistant
stringData:
  smartthings_api_key: ENC[AES256_GCM,data:eVNIdKRujAblTKodEil1vl50pD6yhaKOLOjmPHqsa+ZSJUGm,iv:Frq7X32APrDELgofqUshaAtBZMipt+tl2Kg01sdLOmQ=,tag:Zd5fuxpxVbPdbpd+32OtfQ==,type:str]
sops:
  age:
    - recipient: age1qneprk3zf33h2kjfhmqnnf72kxkj9fplnnkmg26xwp9nx2njtfns2v9mte
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dy8rdlZZdy9tQm1pNzhS
        L3lSN1FmeDJZMmtnZE8yZTFJa3huZ3I1T0U0ClliWUN5R1pJN2k3eE1SUVBRZGND
        Yk9HajIxR3lZcHRnSlhmRVZjbmxqSlkKLS0tIGJ5MDF3Q3gzVnh4akhiVEo5SXN2
        ZmRwbEF6SmRHeEM0NEhJdVRhQU9XUFEK5Znc9/oxhBWackdkJ1ZaTZL60ybOt2Le
        xFkYBJuVRoApyYIKzMbWJlWuNrJIPbKD787CIpoE/E/3hknD13pa7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T20:21:56Z"
  mac: ENC[AES256_GCM,data:mgWWAFpaqa+lDiJZoXup35kyw5rBQ6+MncBHGIPATdt8t8HfXvACKBfq/zvgvzYVm/c3lhhwkn2kOVG/8W548YqgWA8OifzVqAZuJEn3nC/88rd/yKTWYLue4folaByVwMsBx6bQWVg4bYHq77+eTqYi2dAOCzV0Fm8qILMS1Do=,iv:87/M8bcFgf1nI/Kelwzkd92kPGA3elwOeJFLCFlGqHk=,tag:NAJSwK8KQ2Bby4MOcb09Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
