---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
- ../../components/sops
- ../../components/repos/app-template

resources:
- ./namespace.yaml
- ./cloudflare-dns/ks.yaml
- ./cloudflare-tunnel/ks.yaml
- ./envoy-gateway/ks.yaml
- ./external-dns-unifi/ks.yaml
- ./k8s-gateway/ks.yaml
- ./multus/ks.yaml
